# -*- coding: utf-8 -*-
"""que va a pasar en el mercado?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ry70xPRFW-OkVr6XXPQ-I6m9XJu9EiMC
"""

# ===== CELDA 1: Instalar librerías =====
!pip -q install yfinance pandas_datareader openpyxl scikit-learn

# ===== CELDA 2: Imports + parámetros =====
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import yfinance as yf

from pandas_datareader import data as pdr
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from datetime import datetime, timedelta

# --------- Parámetros clave ----------
FOCUS_YEARS = 5                 # conclusiones: últimos 5 años
DOWNLOAD_YEARS = 12             # descargamos más para que haya margen
HORIZON_BDAYS = 5               # "siguientes 5 días hábiles"

END = pd.Timestamp.today(tz="UTC").tz_convert(None).normalize()
START = END - pd.DateOffset(years=DOWNLOAD_YEARS)
FOCUS_START = END - pd.DateOffset(years=FOCUS_YEARS)

print("Descarga:", START.date(), "->", END.date())
print("Focus:", FOCUS_START.date(), "->", END.date())
print("Horizonte:", HORIZON_BDAYS, "días hábiles")

# ===== CELDA 3: Universo + nombres completos + fallbacks =====

# Activos y sectores (lo que quieres sí o sí)
ASSETS_PRIMARY = {
    "SPY": ("S&P 500 (ETF SPY)", ["SPY"]),
    "QQQ": ("Nasdaq 100 (ETF QQQ)", ["QQQ", "^NDX"]),
    "GLD": ("Oro (ETF GLD)", ["GLD", "GC=F"]),
    "SLV": ("Plata (ETF SLV)", ["SLV", "SI=F"]),
}

SECTORS_PRIMARY = {
    "XLC": ("Sector Comunicación (Communication Services)", ["XLC"]),
    "XLY": ("Sector Consumo Discrecional (Consumer Discretionary)", ["XLY"]),
    "XLP": ("Sector Consumo Básico (Consumer Staples)", ["XLP"]),
    "XLE": ("Sector Energía (Energy)", ["XLE"]),
    "XLF": ("Sector Financiero (Financials)", ["XLF"]),
    "XLV": ("Sector Salud (Health Care)", ["XLV"]),
    "XLI": ("Sector Industriales (Industrials)", ["XLI"]),
    "XLB": ("Sector Materiales (Materials)", ["XLB"]),
    "XLRE": ("Sector Bienes Raíces (Real Estate)", ["XLRE"]),
    "XLK": ("Sector Tecnología (Technology)", ["XLK"]),
    "XLU": ("Sector Utilities (Servicios Públicos)", ["XLU"]),
}

# FX / fortaleza USD y peso
FX_PRIMARY = {
    "USDMXN": ("Tipo de cambio USD/MXN", ["MXN=X"]),
    "DXY": ("Fortaleza del dólar (Dollar Index DXY)", ["DX-Y.NYB", "^DXY"]),
    "UUP": ("ETF del dólar (UUP, proxy de USD)", ["UUP"]),
}

# Commodities / macro-asset adicional
EXTRA_PRIMARY = {
    "WTI": ("Petróleo WTI (proxy)", ["CL=F", "USO"]),
}

# Diccionario final (clave interna -> (nombre completo, [tickers posibles]))
UNIVERSE = {}
UNIVERSE.update(ASSETS_PRIMARY)
UNIVERSE.update(SECTORS_PRIMARY)
UNIVERSE.update(FX_PRIMARY)
UNIVERSE.update(EXTRA_PRIMARY)

# Lista de todos los tickers posibles a intentar (para precargar)
ALL_POSSIBLE_TICKERS = sorted(set(t for _, (_, lst) in UNIVERSE.items() for t in lst))

FULL_NAME = {k: v[0] for k, v in UNIVERSE.items()}

print("Tickers Yahoo posibles:", len(ALL_POSSIBLE_TICKERS))
print(ALL_POSSIBLE_TICKERS[:20], "...")

# ===== CELDA 4: Descarga Yahoo robusta con fallbacks =====

def _download_one_ticker(ticker, start, end, auto_adjust=True):
    df = yf.download(
        tickers=ticker,
        start=start,
        end=end + pd.Timedelta(days=1),   # end es exclusivo en yfinance
        auto_adjust=auto_adjust,
        progress=False,
        threads=False,
        group_by="column"
    )
    if df is None or len(df) == 0:
        return pd.Series(dtype=float)
    if isinstance(df.columns, pd.MultiIndex):
        s = df["Close"][ticker].copy() if ticker in df["Close"].columns else df["Close"].iloc[:,0].copy()
    else:
        s = df["Close"].copy() if "Close" in df.columns else df.iloc[:,0].copy()
    s = s.dropna()
    s.name = ticker
    return s

def download_universe_yahoo(universe_dict, start, end, auto_adjust=True, min_points=200):
    """
    Para cada clave (ej. 'DXY'), intenta tickers en orden hasta que uno funcione.
    Retorna:
      - prices_df: columnas por clave (SPY, DXY, etc.)
      - chosen: ticker elegido por clave
      - missing: claves que no lograron bajar
    """
    prices = pd.DataFrame()
    chosen = {}
    missing = []

    for key, (full_name, tickers) in universe_dict.items():
        best = pd.Series(dtype=float)
        best_ticker = None

        for tkr in tickers:
            s = _download_one_ticker(tkr, start, end, auto_adjust=auto_adjust)
            if s is not None and s.dropna().shape[0] >= min_points:
                best = s
                best_ticker = tkr
                break

        if best_ticker is None:
            missing.append(key)
            chosen[key] = None
            prices[key] = np.nan
        else:
            chosen[key] = best_ticker
            prices[key] = best

    prices = prices.sort_index()
    # quitar última fila si es pura NaN (a veces aparece un día extra)
    if prices.tail(1).isna().all(axis=1).iloc[0]:
        prices = prices.iloc[:-1]

    return prices, chosen, missing

prices_all, chosen_ticker, missing_keys = download_universe_yahoo(UNIVERSE, START, END, auto_adjust=True)

print("Elegidos (Yahoo):")
for k in UNIVERSE.keys():
    print(f"- {k}: {FULL_NAME[k]}  | ticker={chosen_ticker.get(k)}")

if missing_keys:
    print("\n⚠️ No se pudieron bajar estas series de Yahoo:")
    for k in missing_keys:
        print(f"- {k}: {FULL_NAME[k]}")
else:
    print("\n✅ Todo Yahoo ok.")

print("\nShape precios:", prices_all.shape)
prices_all.tail(3)

# ===== CELDA 5: Descarga FRED robusta con alternativas =====

# NOTA: FRED no requiere API key para la mayoría, pero puede fallar por conexión.
# Implementamos "listas de fallbacks" por indicador.

FRED_CANDIDATES = {
    # EUA tasas / curva
    "EFFR": ( "Tasa Fed Funds efectiva (EFFR)", ["EFFR", "DFF"] ),
    "UST_2Y": ("Treasury 2 años (yield)", ["DGS2"] ),
    "UST_10Y":("Treasury 10 años (yield)", ["DGS10"] ),
    "UST_3M": ("Treasury 3 meses (yield)", ["TB3MS", "DGS3MO"] ),

    # EUA inflación (niveles para YoY)
    "CPI_US": ("CPI EUA (nivel)", ["CPIAUCSL"] ),
    "CORE_CPI_US": ("Core CPI EUA (nivel)", ["CPILFESL"] ),
    "PCEPI": ("PCE Price Index EUA (nivel)", ["PCEPI"] ),
    "PCEPILFE": ("Core PCE Price Index EUA (nivel)", ["PCEPILFE"] ),

    # EUA actividad/consumo/empleo
    "UNRATE_US": ("Desempleo EUA", ["UNRATE"] ),
    "PAYEMS_US": ("Empleo no agrícola EUA (PAYEMS)", ["PAYEMS"] ),
    "INDPRO_US": ("Producción industrial EUA", ["INDPRO"] ),
    "RETAIL_US": ("Ventas minoristas EUA", ["RSXFS"] ),
    "PCE_REAL": ("Consumo real EUA (PCE real)", ["PCEC96"] ),
    "SENT_US": ("Sentimiento del consumidor EUA (UMich)", ["UMCSENT"] ),
    "ISM_PMI": ("ISM PMI manufacturero EUA", ["NAPM"] ),
    "ICSA": ("Solicitudes iniciales de desempleo EUA (claims)", ["ICSA"] ),
    "HOUST": ("Housing starts EUA", ["HOUST"] ),
    "PERMIT": ("Building permits EUA", ["PERMIT"] ),

    # Riesgo/condiciones
    "NFCI": ("Índice de condiciones financieras (NFCI)", ["NFCI"] ),
    "HY_SPREAD": ("Spread high-yield (OAS)", ["BAMLH0A0HYM2"] ),
    "BAA": ("Yield corporativo Baa", ["BAA"] ),

    # Inflación esperada (breakeven)
    "BE_5Y": ("Breakeven inflación 5Y", ["T5YIE"] ),
    "BE_10Y": ("Breakeven inflación 10Y", ["T10YIE"] ),

    # Fortaleza USD alternativa (por si DXY falla)
    "USD_BROAD": ("Índice dólar amplio (trade-weighted)", ["DTWEXBGS"] ),

    # Liquidez
    "M2": ("M2 EUA", ["M2SL"] ),

    # México (FRED suele tener series OECD/INEGI/Banxico; a veces fallan)
    "CPI_MX_YOY": ("Inflación México (YoY)", ["CPALTT01MXM659N"] ),
    "MX_3M": ("Tasa México 3M (proxy)", ["IR3TIB01MXM156N"] ),
    "MX_10Y": ("Bono México 10Y (proxy)", ["IRLTLT01MXM156N"] ),
}

def fred_try_series(series_id, start, end):
    try:
        s = pdr.DataReader(series_id, "fred", start, end)[series_id]
        return s.dropna()
    except Exception:
        return pd.Series(dtype=float)

def download_fred_candidates(candidates_dict, start, end):
    data = {}
    chosen = {}
    missing = []

    for key, (full_name, series_list) in candidates_dict.items():
        best = pd.Series(dtype=float)
        best_id = None

        for sid in series_list:
            s = fred_try_series(sid, start, end)
            if s is not None and s.dropna().shape[0] >= 10:
                best = s
                best_id = sid
                break

        if best_id is None:
            missing.append(key)
            chosen[key] = None
            data[key] = pd.Series(dtype=float)
        else:
            chosen[key] = best_id
            data[key] = best

    df = pd.DataFrame(data).sort_index()
    return df, chosen, missing

macro_raw, fred_chosen, fred_missing = download_fred_candidates(FRED_CANDIDATES, START, END)

print("Elegidos (FRED):")
for k in FRED_CANDIDATES.keys():
    print(f"- {k}: {FRED_CANDIDATES[k][0]}  | series={fred_chosen.get(k)}")

if fred_missing:
    print("\n⚠️ No se pudieron bajar estas series de FRED:")
    for k in fred_missing:
        print(f"- {k}: {FRED_CANDIDATES[k][0]}")
else:
    print("\n✅ Todo FRED ok.")

print("\nMacro raw shape:", macro_raw.shape)
macro_raw.tail(3)

# ===== CELDA 6: Features diarios + alineación =====

# Base diaria: mismos días que precios
bdays = prices_all.index.copy()

macro = macro_raw.reindex(bdays).ffill()

# Inflación YoY EUA (con niveles mensuales -> ffill)
def yoy_from_level(level_series, periods=252):
    # para dataset diario: aproximamos "12 meses" como 252 días hábiles
    return (level_series / level_series.shift(periods) - 1) * 100

macro["CPI_US_YOY"] = yoy_from_level(macro.get("CPI_US"), 252)
macro["CORE_CPI_US_YOY"] = yoy_from_level(macro.get("CORE_CPI_US"), 252)
macro["PCE_YOY"] = yoy_from_level(macro.get("PCEPI"), 252)
macro["CORE_PCE_YOY"] = yoy_from_level(macro.get("PCEPILFE"), 252)

# Curva EUA
macro["YC_10Y_2Y"] = macro["UST_10Y"] - macro["UST_2Y"]
macro["YC_10Y_3M"] = macro["UST_10Y"] - macro["UST_3M"]

# Spread Baa - 10Y
macro["BAA_10Y_SPREAD"] = macro["BAA"] - macro["UST_10Y"]

# Curva México (si hay datos)
macro["MX_YC_10Y_3M"] = macro["MX_10Y"] - macro["MX_3M"]

# FX + fortaleza del peso
fx = prices_all[["USDMXN","DXY","UUP"]].copy()
fx["MXNUSD"] = 1.0 / fx["USDMXN"]

# Si DXY vino con muchos NaN, usamos USD_BROAD (FRED) como "fortaleza USD"
if fx["DXY"].dropna().shape[0] < 200:
    usd_broad = macro.get("USD_BROAD")
    if usd_broad is not None and usd_broad.dropna().shape[0] > 50:
        # normalizamos a "índice" comparable: reescalado
        fx["DXY"] = usd_broad.reindex(bdays).ffill()
        print("✅ DXY reemplazado por USD_BROAD (FRED) como proxy de fortaleza USD.")
    else:
        print("⚠️ No hay DXY ni USD_BROAD suficientes. La 'fortaleza USD' quedará incompleta.")

# Features: niveles + cambios 1 mes (~21 bdays)
def delta(x, n=21):
    return x - x.shift(n)

features = pd.DataFrame(index=bdays)

# Precios macro-asset (solo como info)
features["Fortaleza del dólar (índice)"] = fx["DXY"]
features["Tipo de cambio USD/MXN"] = fx["USDMXN"]
features["Fortaleza del peso (MXN/USD)"] = fx["MXNUSD"]
features["Petróleo WTI (precio)"] = prices_all["WTI"]

# Macro niveles clave
add_map = {
    "EFFR": "Tasa EUA (EFFR)",
    "UST_2Y": "Yield EUA 2 años",
    "UST_10Y": "Yield EUA 10 años",
    "UST_3M": "Yield EUA 3 meses",
    "YC_10Y_2Y": "Curva EUA 10Y-2Y",
    "YC_10Y_3M": "Curva EUA 10Y-3M",
    "CPI_US_YOY": "Inflación EUA (CPI YoY)",
    "CORE_CPI_US_YOY": "Inflación subyacente EUA (Core CPI YoY)",
    "PCE_YOY": "Inflación EUA (PCE YoY)",
    "CORE_PCE_YOY": "Inflación subyacente EUA (Core PCE YoY)",
    "UNRATE_US": "Desempleo EUA",
    "ICSA": "Claims semanales EUA",
    "INDPRO_US": "Producción industrial EUA",
    "RETAIL_US": "Ventas minoristas EUA",
    "PCE_REAL": "Consumo real EUA (PCE real)",
    "SENT_US": "Sentimiento consumidor EUA",
    "ISM_PMI": "ISM PMI EUA",
    "HOUST": "Housing starts EUA",
    "PERMIT": "Building permits EUA",
    "NFCI": "Condiciones financieras (NFCI)",
    "HY_SPREAD": "Spread High Yield (OAS)",
    "BAA_10Y_SPREAD": "Spread Baa - 10Y EUA",
    "BE_5Y": "Breakeven inflación 5Y",
    "BE_10Y": "Breakeven inflación 10Y",
    "M2": "M2 EUA",
    "CPI_MX_YOY": "Inflación México (YoY)",
    "MX_3M": "Tasa México 3M (proxy)",
    "MX_10Y": "Bono México 10Y (proxy)",
    "MX_YC_10Y_3M": "Curva México 10Y-3M (proxy)",
}

for k, nice in add_map.items():
    if k in macro.columns:
        features[nice] = macro[k]

# Cambios 1 mes (momentum macro)
for nice_col in list(features.columns):
    if nice_col in ["Fortaleza del dólar (índice)", "Tipo de cambio USD/MXN", "Petróleo WTI (precio)"]:
        features[f"Cambio 1m: {nice_col}"] = delta(features[nice_col], 21)

# Cambios 1m para macro numérica
for nice in add_map.values():
    if nice in features.columns:
        features[f"Cambio 1m: {nice}"] = delta(features[nice], 21)

# Limpiar
features = features.sort_index()
print("Features shape:", features.shape)
features.tail(2)

# ===== CELDA 7: Forward returns 5d + dataset =====

# Precios de activos/sectores
asset_keys = list(ASSETS_PRIMARY.keys()) + list(SECTORS_PRIMARY.keys())
asset_px = prices_all[asset_keys].copy()

# Forward return 5 días hábiles (log)
fwd = np.log(asset_px.shift(-HORIZON_BDAYS) / asset_px)
fwd_cols = {c: f"Forward 5d: {FULL_NAME[c]}" for c in fwd.columns}
fwd = fwd.rename(columns=fwd_cols)

# Dataset final
df = features.join(fwd, how="left")

# Focus últimos 5 años
df5 = df[df.index >= FOCUS_START].copy()

print("Dataset total:", df.shape, "| Focus 5y:", df5.shape)

# Tabla de disponibilidad (qué tiene datos suficientes en 5y)
availability = pd.DataFrame(index=asset_keys, columns=["Nombre completo", "Datos en 5y", "Último dato"])
for k in asset_keys:
    col = f"Forward 5d: {FULL_NAME[k]}"
    availability.loc[k, "Nombre completo"] = FULL_NAME[k]
    availability.loc[k, "Datos en 5y"] = int(df5[col].dropna().shape[0])
    availability.loc[k, "Último dato"] = str(asset_px[k].dropna().index.max().date()) if asset_px[k].dropna().shape[0] else "NA"

availability = availability.sort_values("Datos en 5y", ascending=False)
display(availability)

# ===== CELDA 8: Correlaciones claras (5y) =====

# Selección de features (quitamos columnas 100% vacías)
feat_cols = [c for c in features.columns if df5[c].dropna().shape[0] > 200]
target_cols = [c for c in fwd.columns if df5[c].dropna().shape[0] > 200]

corr = df5[feat_cols + target_cols].corr()
corr_ft = corr.loc[feat_cols, target_cols].copy()

stacked = corr_ft.stack().dropna().sort_values()
top_neg = stacked.head(25)
top_pos = stacked.tail(25)

def pretty_corr_list(series, n=10, ascending=False):
    s = series.sort_values(ascending=ascending).head(n) if ascending else series.sort_values(ascending=False).head(n)
    rows = []
    for (feat, tgt), v in s.items():
        rows.append({
            "Correlación": float(v),
            "Indicador (feature)": feat,
            "Activo/sector (target)": tgt.replace("Forward 5d: ", "")
        })
    return pd.DataFrame(rows)

print("TOP correlaciones POSITIVAS (feature -> retorno 5d):")
display(pretty_corr_list(top_pos, n=12, ascending=False))

print("TOP correlaciones NEGATIVAS (feature -> retorno 5d):")
display(pretty_corr_list(top_neg, n=12, ascending=True))

# ===== CELDA 9: Probabilidades por 'días parecidos' (kNN simple) =====

# Elegimos ejes de estado (macro/FX) para buscar días parecidos
STATE_FEATURES = [
    "Tasa EUA (EFFR)",
    "Yield EUA 10 años",
    "Curva EUA 10Y-3M",
    "Inflación EUA (CPI YoY)",
    "Claims semanales EUA",
    "Condiciones financieras (NFCI)",
    "Spread High Yield (OAS)",
    "Breakeven inflación 5Y",
    "Fortaleza del dólar (índice)",
    "Tipo de cambio USD/MXN",
    "Petróleo WTI (precio)",
]

# mantener solo las que existan
STATE_FEATURES = [c for c in STATE_FEATURES if c in df5.columns and df5[c].dropna().shape[0] > 200]
print("STATE_FEATURES usados:", STATE_FEATURES)

# Última fecha utilizable ("hoy"): que tenga valores de estado
today_idx = df5.dropna(subset=STATE_FEATURES, how="any").index.max()
print("Fecha 'hoy' usada:", today_idx.date())

# Estandarizar estado con stats del periodo 5y
X = df5[STATE_FEATURES].dropna().copy()
mu = X.mean()
sd = X.std(ddof=0).replace(0, np.nan)

z = (X - mu) / sd
z_today = ((df5.loc[today_idx, STATE_FEATURES] - mu) / sd).astype(float)

# Distancia y vecinos
dist = ((z - z_today)**2).sum(axis=1)**0.5
K = 150  # vecinos
neighbors_idx = dist.sort_values().head(K).index

neighbors = df5.loc[neighbors_idx, target_cols].dropna(how="all")
# Distribución de retornos futuros en vecinos
knn_mean = neighbors.mean().sort_values(ascending=False)
knn_p_pos = (neighbors > 0).mean().sort_values(ascending=False)
knn_p10 = neighbors.quantile(0.10).sort_values(ascending=False)
knn_p50 = neighbors.quantile(0.50).sort_values(ascending=False)
knn_p90 = neighbors.quantile(0.90).sort_values(ascending=False)

summary_knn = pd.DataFrame({
    "Retorno esperado (promedio)": knn_mean,
    "Probabilidad de subir (>0)": knn_p_pos,
    "P10": knn_p10,
    "P50 (mediana)": knn_p50,
    "P90": knn_p90
}).sort_values("Probabilidad de subir (>0)", ascending=False)

print("Resumen por días parecidos (historia 5y) — TOP 12:")
display(summary_knn.head(12))

# ===== CELDA 10: Modelo probabilístico + explicación =====

# Features para modelo (estado + cambios 1m)
MODEL_FEATURES = STATE_FEATURES.copy()

# añadimos algunos cambios 1m si existen
for c in list(df5.columns):
    if c.startswith("Cambio 1m: ") and (df5[c].dropna().shape[0] > 200):
        # agregamos cambios que correspondan a features relevantes
        if any(base in c for base in ["Tasa EUA", "Yield EUA", "Curva EUA", "Inflación EUA", "Claims", "NFCI", "High Yield", "Breakeven", "Fortaleza del dólar", "USD/MXN", "Petróleo"]):
            MODEL_FEATURES.append(c)

# Deduplicar
MODEL_FEATURES = list(dict.fromkeys(MODEL_FEATURES))
print("MODEL_FEATURES:", len(MODEL_FEATURES))

# Pipeline
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=2000))
])

def train_predict_with_explain(target_col, min_train=900):
    """
    target_col: columna de forward return (ej. 'Forward 5d: Oro (ETF GLD)')
    Devuelve probabilidad de subir hoy y explicación (top drivers).
    """
    d = df5[MODEL_FEATURES + [target_col]].dropna().copy()
    if len(d) < min_train:
        return np.nan, [], len(d)

    y = (d[target_col] > 0).astype(int).values
    X = d[MODEL_FEATURES].values

    # Entrenar con todo menos el último punto
    pipe.fit(X[:-1], y[:-1])

    # Predecir en el último punto (que corresponde a "hoy" del dataset recortado)
    x_last = X[-1:]
    p_up = float(pipe.predict_proba(x_last)[0,1])

    # Explicación: contribuciones = coef * z (en espacio estandarizado)
    scaler = pipe.named_steps["scaler"]
    lr = pipe.named_steps["lr"]

    z_last = scaler.transform(x_last)[0]
    coefs = lr.coef_[0]
    contrib = coefs * z_last

    # Top 3 drivers positivos y negativos
    idx_sorted = np.argsort(np.abs(contrib))[::-1]
    top = []
    for i in idx_sorted[:6]:
        feat = MODEL_FEATURES[i]
        sign = "↑" if contrib[i] > 0 else "↓"
        # valor actual vs mediana 5y
        cur = df5.loc[d.index[-1], feat]
        med = df5[feat].median()
        rel = "por encima de" if cur > med else "por debajo de"
        top.append((feat, sign, float(contrib[i]), float(cur) if pd.notna(cur) else None, rel, float(med) if pd.notna(med) else None))

    return p_up, top, len(d)

# Calcular probabilidades para cada activo/sector
results = []
explanations = {}

for k in asset_keys:
    target = f"Forward 5d: {FULL_NAME[k]}"
    p_up, top, nobs = train_predict_with_explain(target)
    results.append({
        "Activo/Sector": FULL_NAME[k],
        "Probabilidad de subir en 5 días": p_up,
        "Observaciones usadas (5y)": nobs
    })
    explanations[FULL_NAME[k]] = top

probs_df = pd.DataFrame(results).sort_values("Probabilidad de subir en 5 días", ascending=False)

print("Probabilidades (modelo) — TOP 12:")
display(probs_df.head(12))

# ===== CELDA 11: Conclusiones claras + Excel =====

# 1) Valores actuales (para “toma en cuenta tasas/precios actuales”)
def last_value(series):
    s = series.dropna()
    return (s.index.max(), float(s.iloc[-1])) if len(s) else (None, None)

current_lines = []
current_lines.append(f"FECHA USADA COMO 'HOY' (último dato utilizable): {today_idx.date()}")
current_lines.append("")
current_lines.append("LECTURA DE CONDICIONES ACTUALES (niveles más recientes):")

# principales indicadores
key_readouts = [
    "Tasa EUA (EFFR)",
    "Yield EUA 10 años",
    "Curva EUA 10Y-3M",
    "Inflación EUA (CPI YoY)",
    "Claims semanales EUA",
    "Condiciones financieras (NFCI)",
    "Spread High Yield (OAS)",
    "Breakeven inflación 5Y",
    "Fortaleza del dólar (índice)",
    "Tipo de cambio USD/MXN",
    "Petróleo WTI (precio)",
    "Inflación México (YoY)",
    "Tasa México 3M (proxy)",
]
for k in key_readouts:
    if k in df5.columns:
        v = df5.loc[today_idx, k]
        current_lines.append(f"- {k}: {v:.4f}" if pd.notna(v) else f"- {k}: NA")

# 2) Conclusión 1: correlaciones más importantes (humanas)
concl1 = []
concl1.append("CONCLUSIÓN 1 — Correlaciones más importantes (últimos 5 años, retorno a 5 días)")
concl1.append("")
concl1.append("Estas son relaciones históricas (NO causales). Te sirven para entender qué indicadores tienden a moverse con qué activos/sectores a corto plazo.")
concl1.append("")
concl1.append("TOP 10 correlaciones POSITIVAS (cuando el indicador sube, tiende a subir el retorno 5d):")
for (feat, tgt), v in top_pos.sort_values(ascending=False).head(10).items():
    concl1.append(f"- {tgt.replace('Forward 5d: ', '')}: correlación {v:+.3f} con '{feat}'")

concl1.append("")
concl1.append("TOP 10 correlaciones NEGATIVAS (cuando el indicador sube, tiende a bajar el retorno 5d):")
for (feat, tgt), v in top_neg.sort_values(ascending=True).head(10).items():
    concl1.append(f"- {tgt.replace('Forward 5d: ', '')}: correlación {v:+.3f} con '{feat}'")

# 3) Conclusión 2: “lo más probable” próximos 5 días (hoy)
# Mezclamos: (a) vecinos parecidos + (b) modelo con explicación
concl2 = []
concl2.append("CONCLUSIÓN 2 — Qué es lo más probable en los próximos 5 días (con datos actuales + historia 5 años)")
concl2.append("")
concl2.append("Voy a combinar dos lentes:")
concl2.append("A) Días históricos parecidos (k vecinos): te da probabilidad empírica y rangos (P10/P50/P90).")
concl2.append("B) Modelo probabilístico (logístico): te da probabilidad y 'por qué' (factores que hoy empujan la señal).")
concl2.append("")

# Top 3 por modelo
top3 = probs_df.dropna(subset=["Probabilidad de subir en 5 días"]).head(3)
bottom3 = probs_df.dropna(subset=["Probabilidad de subir en 5 días"]).tail(3)

def pct(x):
    return f"{100*x:.0f}%" if pd.notna(x) else "NA"

concl2.append("🔼 MÁS PROBABLE QUE SUBA (según el modelo) en 5 días:")
for _, r in top3.iterrows():
    name = r["Activo/Sector"]
    p = r["Probabilidad de subir en 5 días"]
    concl2.append(f"- La probabilidad de que {name} suba en los próximos 5 días es {pct(p)}.")
    # razones (top drivers)
    drivers = explanations.get(name, [])
    if drivers:
        concl2.append("  Principales razones (señales actuales vs mediana 5 años):")
        for feat, sign, contrib, cur, rel, med in drivers[:3]:
            # sign indica si empuja a subir o bajar
            concl2.append(f"  • {feat}: hoy está {rel} su mediana 5y ({cur:.4f} vs {med:.4f}) y esto empuja la probabilidad {('al alza' if sign=='↑' else 'a la baja')}.")
    # kNN info si existe
    knn_row = summary_knn.loc[summary_knn.index == f"Forward 5d: {name}"]
    if len(knn_row):
        rr = knn_row.iloc[0]
        concl2.append(f"  En días parecidos (historia 5y): P(subir)≈{pct(rr['Probabilidad de subir (>0)'])}, retorno esperado≈{rr['Retorno esperado (promedio)']:+.4f} (P10={rr['P10']:+.4f}, P90={rr['P90']:+.4f}).")
    concl2.append("")

concl2.append("🔽 MÁS PROBABLE QUE BAJE (según el modelo) en 5 días:")
for _, r in bottom3.iterrows():
    name = r["Activo/Sector"]
    p = r["Probabilidad de subir en 5 días"]
    concl2.append(f"- La probabilidad de que {name} suba en los próximos 5 días es baja ({pct(p)}), así que el escenario más probable es débil/negativo.")
    drivers = explanations.get(name, [])
    if drivers:
        concl2.append("  Principales razones (señales actuales vs mediana 5 años):")
        for feat, sign, contrib, cur, rel, med in drivers[:3]:
            concl2.append(f"  • {feat}: hoy está {rel} su mediana 5y ({cur:.4f} vs {med:.4f}) y esto empuja la probabilidad {('al alza' if sign=='↑' else 'a la baja')}.")
    knn_row = summary_knn.loc[summary_knn.index == f"Forward 5d: {name}"]
    if len(knn_row):
        rr = knn_row.iloc[0]
        concl2.append(f"  En días parecidos (historia 5y): P(subir)≈{pct(rr['Probabilidad de subir (>0)'])}, retorno esperado≈{rr['Retorno esperado (promedio)']:+.4f} (P10={rr['P10']:+.4f}, P90={rr['P90']:+.4f}).")
    concl2.append("")

# 4) Export Excel con todo + reporte de faltantes
out_path = "ESTUDIO_MACRO_5D_US_MX.xlsx"

missing_report = []
missing_report.append("MISSING YAHOO:")
if missing_keys:
    for k in missing_keys:
        missing_report.append(f"- {k}: {FULL_NAME[k]}")
else:
    missing_report.append("- Ninguno")

missing_report.append("")
missing_report.append("MISSING FRED:")
if fred_missing:
    for k in fred_missing:
        missing_report.append(f"- {k}: {FRED_CANDIDATES[k][0]}")
else:
    missing_report.append("- Ninguno")

# tablas útiles para Excel
top_pos_tbl = pretty_corr_list(top_pos, n=25, ascending=False)
top_neg_tbl = pretty_corr_list(top_neg, n=25, ascending=True)

with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    prices_all.to_excel(writer, sheet_name="PRICES_YAHOO_DAILY")
    macro_raw.to_excel(writer, sheet_name="MACRO_FRED_RAW")
    features.to_excel(writer, sheet_name="FEATURES_DAILY")
    fwd.to_excel(writer, sheet_name="FORWARD_5D")
    availability.to_excel(writer, sheet_name="AVAILABILITY_5Y")
    corr_ft.to_excel(writer, sheet_name="CORR_FEATURE_TO_5D")
    top_pos_tbl.to_excel(writer, sheet_name="TOP_CORR_POS", index=False)
    top_neg_tbl.to_excel(writer, sheet_name="TOP_CORR_NEG", index=False)
    summary_knn.to_excel(writer, sheet_name="KNN_SIMILAR_DAYS")
    probs_df.to_excel(writer, sheet_name="MODEL_PROBS", index=False)

    pd.DataFrame({"texto": current_lines}).to_excel(writer, sheet_name="READOUT_HOY", index=False)
    pd.DataFrame({"texto": concl1}).to_excel(writer, sheet_name="CONCLUSION_1", index=False)
    pd.DataFrame({"texto": concl2}).to_excel(writer, sheet_name="CONCLUSION_2", index=False)
    pd.DataFrame({"texto": missing_report}).to_excel(writer, sheet_name="MISSING_REPORT", index=False)

print("✅ Listo. Excel generado:", out_path)

print("\n" + "="*70)
print("\n".join(current_lines[:20]))
print("\n" + "="*70)
print("\n".join(concl2[:80]))