# -*- coding: utf-8 -*-
"""UMPA ULTRA MEJORADO 2.0 15-01-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4lED8XD2nbDPZJIUHPsKKGN-ZbB3NBw
"""

#SPY, ABNB, GRMN, AIA, QQQ, XLF, XLK, BRK-B, GOOG, MSFT, AMZN, NVDA, META, TSLA, JPM, V, MA, NFLX, WMT, ORCL, CRM, AVGO, TSM, ASML, SAP, AZN, RACE, SONY, HMC, BABA, JD, PDD, KWEB, EWW, EEM, VEU, HYG, LQD, VNQ, IYR, DIA, IWM, XLE, XLY, XLP, XLI, XLB, XLV, XLU, SOXX, SMH, MELI, GLD, T, JNJ, GOOGL, BAC, INTC, AMD, ADBE, AAPL, NKE, QCOM, PYPL, COIN, MSCI, IAU, GRID, MELI, TSM, SHY, TLT, EDV, SHY, BIL, SGOV, IEF, TLT, COST, BRK-A, ABNB, PPA, SLV
# ==============================================
# Celda 1: INSTALACIÓN (1 vez por sesión)
# ==============================================
# En Colab, descomenta la siguiente línea si te faltan paquetes:
!pip -q install yfinance pandas numpy scipy pandas_datareader openpyxl xlsxwriter pyyaml

# ==============================================
# Celda 2: IMPORTS + CONFIG + UTILIDADES BASE
# ==============================================
import numpy as np, pandas as pd, yfinance as yf
from scipy.optimize import minimize
from datetime import datetime, timedelta
import re, math, unicodedata, logging, os, json, pathlib, warnings, statistics
from typing import Tuple, List, Dict, Optional
warnings.filterwarnings("ignore")

# FRED opcional para Rf (USD); si falla, se usa fallback
try:
    from pandas_datareader import data as pdr
    HAS_PDR = True
except Exception:
    HAS_PDR = False

try:
    import yaml
except Exception:
    yaml = None

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("DCF_PORT_V4_CORREGIDO")

# ========= CONFIG por defecto (se puede sobreescribir con CONFIG.yml) =========
CONFIG_DEFAULT = {
    "ETR_CAP_BY_COUNTRY": {  # caps por país
        "Mexico": 0.30, "México": 0.30, "MX": 0.30,
        "United States": 0.21, "USA": 0.21, "US": 0.21,
        "United Kingdom": 0.25, "UK": 0.25,
        "Germany": 0.30, "DE": 0.30,
        "France": 0.28, "FR": 0.28,
        "Japan": 0.30, "JP": 0.30,
        "Canada": 0.26, "CA": 0.26,
        "_DEFAULT": 0.30
    },
    "YEARS_PROJ": 7,               # horizonte explícito para fade (5-10)
    "FADE_METHOD": "linear",       # "linear" o "hmodel"
    "LAMBDA": 0.40,                # peso a la señal DCF en expected returns
    "ERP_BANDS": {"min": 0.035, "max": 0.060, "fallback": 0.055},
    "USD_RF_FALLBACK": 0.04,
    "TERM_GROWTH_DEV": {"USD": [0.015, 0.025], "EUR": [0.015, 0.025]},
    "TERM_GROWTH_EM" : [0.020, 0.035],
    "G_EXPL_BOUNDS": [-0.10, 0.20],
    "PORT_MEMORY_FILE": "portfolios_memory.json",
    "EXCEL_OUT": "resultado_valuacion_portafolio.xlsx"
}

def load_config(path="CONFIG.yml") -> dict:
    """Carga CONFIG.yml si existe, si no usa defaults."""
    cfg = CONFIG_DEFAULT.copy()
    p = pathlib.Path(path)
    if p.exists() and yaml is not None:
        try:
            user_cfg = yaml.safe_load(p.read_text(encoding="utf-8"))
            if isinstance(user_cfg, dict):
                for k, v in user_cfg.items():
                    cfg[k] = v
            log.info("CONFIG.yml cargado.")
        except Exception as e:
            log.warning(f"No se pudo leer CONFIG.yml: {e} — uso defaults.")
    return cfg

CFG = load_config()

# ========= Constantes derivadas de CONFIG =========
YEARS_PROJ = int(CFG["YEARS_PROJ"])
GTERM_DEV  = dict(CFG["TERM_GROWTH_DEV"])
GTERM_EM   = tuple(CFG["TERM_GROWTH_EM"])
MIN_G_EXPL, MAX_G_EXPL = CFG["G_EXPL_BOUNDS"]
ERP_MIN, ERP_MAX = CFG["ERP_BANDS"]["min"], CFG["ERP_BANDS"]["max"]
FALLBACK_ERP = CFG["ERP_BANDS"]["fallback"]
UST10_TICKER = "^TNX"
FRED_10Y     = "DGS10"
XL_OUT       = CFG["EXCEL_OUT"]
PORTFOLIO_DB_FILE = CFG["PORT_MEMORY_FILE"]

# Canonicalización de tickers
CANONICAL_TICKERS = {
    "TSMC": "TSM",
    "BRK.B": "BRK-B",
    "BRK.A": "BRK-A"
}


# Monedas con pennies (GBp→GBP, etc.)
CCY_NORMALIZATION = {"GBp": ("GBP", 0.01), "ZAc": ("ZAR", 0.01)}

def normalize_price_currency(info_currency: str, series: Optional[pd.Series]=None, last_price: Optional[float]=None):
    ccy = (info_currency or "").strip()
    if ccy in CCY_NORMALIZATION:
        ccy_new, factor = CCY_NORMALIZATION[ccy]
        if series is not None: series = series * factor
        if last_price is not None: last_price = last_price * factor
        return ccy_new, series, last_price
    return ccy, series, last_price

def sanitize_symbol(sym: str) -> str:
    if not sym: return sym
    s = str(sym).strip().upper().lstrip("$")
    return s

def _norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", str(s)).encode("ascii","ignore").decode("ascii")
    s = s.lower().replace("&", " and ")
    s = re.sub(r"[^\w\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def fx_pair(a: str, b: str) -> str:
    return f"{a}{b}=X"

def fx_spot(from_ccy: str, to_ccy: str) -> float:
    if not from_ccy or not to_ccy or from_ccy == to_ccy: return 1.0
    try:
        px = yf.Ticker(fx_pair(from_ccy,to_ccy)).history(period="5d", interval="1d")["Close"].dropna()
        return float(px.iloc[-1]) if not px.empty else 1.0
    except Exception:
        return 1.0

def get_fx_series(from_ccy: str, to_ccy: str, start: str) -> pd.Series:
    if not from_ccy or not to_ccy or from_ccy == to_ccy:
        return pd.Series(1.0, index=pd.date_range(start=start, end=datetime.today(), freq="D"))
    for pair, invert in [(fx_pair(from_ccy,to_ccy), False),(fx_pair(to_ccy,from_ccy), True)]:
        try:
            s = yf.Ticker(pair).history(start=start, auto_adjust=False)["Close"].dropna()
            if not s.empty:
                return (1.0/s) if invert else s
        except Exception:
            pass
    return pd.Series(1.0, index=pd.date_range(start=start, end=datetime.today(), freq="D"))

def first_non_nan(arr, default=np.nan):
    for x in (arr or []):
        if x is not None and not (isinstance(x,float) and np.isnan(x)):
            return float(x)
    return default

# ==============================================
# Celda 3: ALIAS + EXTRACCIÓN + NWC + ALL STATEMENTS (CORREGIDA)
# ==============================================
def load_alias_builtin() -> dict:
    alias = {
        # IS
        "revenue":      ["total revenue","revenue","revenues","operating revenue","net sales","sales","turnover"],
        "op_income":    ["operating income","operating profit","ebit","total operating income as reported","income from operations"],
        "da":           ["depreciation and amortization","depreciation","amortization",
                         "depreciation income statement","depreciation and amortization in income statement",
                         "reconciled depreciation","depreciation amortization depletion"],
        "tax_exp":      ["income tax expense","tax provision","provision for income taxes"],
        "interest_exp": ["interest expense","interest expense non operating","net interest expense"],
        "net_income":   ["net income","net income applicable to common shares","consolidated net income","net earnings"],
        "capex":        ["capital expenditure","capital expenditure reported","purchase of ppe",
                         "purchase of property plant and equipment","additions to property plant and equipment"],
        "change_wc_cf": ["change in working capital","change in other working capital"],
        # BS
        "cash_like":    ["cash and cash equivalents","cash equivalents","cash","cash cash equivalents and short term investments"],
        "sti":          ["short term investments","marketable securities"],
        "cash_restricted":["restricted cash"],
        "ar":           ["accounts receivable","trade receivables","net receivables"],
        "inventory":    ["inventory","inventories"],
        "other_ca":     ["other current assets","prepaid expenses","prepaid expenses and other current assets"],
        "ap":           ["accounts payable","trade payables"],
        "other_cl":     ["other current liabilities","accrued expenses","accrued liabilities","other payables"],
        "deferred_rev_cur":["deferred revenue","deferred income","contract liabilities current","unearned revenue"],
        "taxes_payable":["income taxes payable","taxes payable","current income taxes payable"],
        "cur_debt":     ["current portion of long term debt","short term debt","current debt",
                         "current debt and capital lease obligation","short term borrowings","notes payable"],
        "lt_debt":      ["long term debt","long term debt and capital lease obligation","long term borrowings",
                         "long term capital lease obligation"],
        "lease_lt":     ["non current lease liabilities","long term lease liabilities"],
        "lease_cur":    ["current lease liabilities","lease liabilities current"],
        "total_debt":   ["total debt"],
        "equity_total": ["total stockholder equity","total shareholders equity"],
        "tot_ca":       ["total current assets","current assets"],
        "tot_cl":       ["total current liabilities","current liabilities"],
        "ppe_net":      ["property plant equipment","property plant and equipment","net property plant and equipment",
                         "property plant equipment net"]
    }
    return {k: sorted(set(v)) for k,v in alias.items()}

def _compile_patterns(words):
    pats=[]
    for w in words:
        pats.append(w if isinstance(w, re.Pattern) else re.compile(re.escape(_norm(w))))
    return pats

def _match_first_from_patterns(index_like_iterable, patterns):
    if index_like_iterable is None: return None, None
    idx_norm = {_norm(i): i for i in index_like_iterable}
    for pat in patterns:
        for norm_name, original in idx_norm.items():
            if pat.search(norm_name):
                return original, f"regex:{pat.pattern}"
    return None, None

def find_value(df: pd.DataFrame, patterns, col, prefer_nonzero=False):
    name, why = _match_first_from_patterns(df.index if df is not None else [], _compile_patterns(patterns))
    if not name: return np.nan, None, None
    try:
        val = float(df.loc[name, col])
        if prefer_nonzero and (val==0 or np.isnan(val)): return np.nan, None, None
        return val, name, why
    except Exception:
        return np.nan, None, None

def _get_series_from_bs(bal: pd.DataFrame, alias: dict, key: str):
    arr=[]; src=[]
    if bal is None or bal.empty: return arr, src
    for c in bal.columns:
        v, n, why = find_value(bal, alias.get(key,[]), c)
        arr.append(v); src.append((n,why,"BS"))
    return arr, src

def _compute_operating_nwc_arrays(bal: pd.DataFrame, alias: dict):
    cash_like,_   = _get_series_from_bs(bal, alias, "cash_like")
    sti,_         = _get_series_from_bs(bal, alias, "sti")
    cash_res,_    = _get_series_from_bs(bal, alias, "cash_restricted")
    ar,_          = _get_series_from_bs(bal, alias, "ar")
    invt,_        = _get_series_from_bs(bal, alias, "inventory")
    other_ca,_    = _get_series_from_bs(bal, alias, "other_ca")
    ap,_          = _get_series_from_bs(bal, alias, "ap")
    other_cl,_    = _get_series_from_bs(bal, alias, "other_cl")
    cur_debt,_    = _get_series_from_bs(bal, alias, "cur_debt")
    lease_cur,_   = _get_series_from_bs(bal, alias, "lease_cur")
    tot_ca,_      = _get_series_from_bs(bal, alias, "tot_ca")
    tot_cl,_      = _get_series_from_bs(bal, alias, "tot_cl")
    defrev,_      = _get_series_from_bs(bal, alias, "deferred_rev_cur")
    taxpay,_      = _get_series_from_bs(bal, alias, "taxes_payable")

    def nz(x):
        return 0.0 if (x is None or (isinstance(x,float) and np.isnan(x))) else float(x)

    N = len(bal.columns) if (bal is not None and not bal.empty) else 0
    if N == 0: return [], [], "NO_BS"

    OCA, OCL = [], []
    used_totals=False; used_components=False

    for i in range(N):
        ca_t = tot_ca[i] if i<len(tot_ca) else np.nan
        cl_t = tot_cl[i] if i<len(tot_cl) else np.nan

        if not np.isnan(ca_t):
            oca = nz(ca_t) - nz(cash_like[i] if i<len(cash_like) else np.nan) \
                           - nz(sti[i] if i<len(sti) else np.nan) \
                           - nz(cash_res[i] if i<len(cash_res) else np.nan)
            used_totals=True
        else:
            oca = nz(ar[i] if i<len(ar) else np.nan) + nz(invt[i] if i<len(invt) else np.nan) + nz(other_ca[i] if i<len(other_ca) else np.nan)
            used_components=True

        if not np.isnan(cl_t):
            ocl = nz(cl_t) - nz(cur_debt[i] if i<len(cur_debt) else np.nan) - nz(lease_cur[i] if i<len(lease_cur) else np.nan)
        else:
            ocl = nz(ap[i] if i<len(ap) else np.nan) + nz(other_cl[i] if i<len(other_cl) else np.nan) \
                + nz(defrev[i] if i<len(defrev) else np.nan) + nz(taxpay[i] if i<len(taxpay) else np.nan)
            used_components=True

        OCA.append(oca); OCL.append(ocl)

    NWC = np.array([OCA[i]-OCL[i] for i in range(N)], dtype=float)
    delta = np.array([np.nan]*N, dtype=float)
    for k in range(0, max(0, N-1)):
        if not np.isnan(NWC[k]) and not np.isnan(NWC[k+1]):
            delta[k] = NWC[k] - NWC[k+1]

    src = "BS_total" if used_totals else ("BS_components" if used_components else "BS")
    return NWC, delta, src

def extract_time_series_v4(tk: yf.Ticker, yrs_hist: int, alias: dict) -> dict:
    inc = tk.financials.iloc[:, :yrs_hist] if tk.financials is not None else pd.DataFrame()
    bal = tk.balance_sheet.iloc[:, :yrs_hist] if tk.balance_sheet is not None else pd.DataFrame()
    cf  = tk.cashflow.iloc[:, :yrs_hist] if tk.cashflow is not None else pd.DataFrame()

    if inc.empty and bal.empty and cf.empty:
        return {"_no_statements_": True}

    cols = list(inc.columns if not inc.empty else (cf.columns if not cf.empty else bal.columns))
    revenue=[]; ebit=[]; tax_exp=[]; da_is=[]; int_exp=[]; net_income=[]

    for c in cols:
        v,_n,_w = find_value(inc, alias["revenue"], c);      revenue.append(v)
        v,_n,_w = find_value(inc, alias["op_income"], c);    ebit.append(v)
        v,_n,_w = find_value(inc, alias["tax_exp"], c);      tax_exp.append(v)
        v,_n,_w = find_value(inc, alias["da"], c);           da_is.append(v)
        v,_n,_w = find_value(inc, alias["interest_exp"], c); int_exp.append(v)
        v,_n,_w = find_value(inc, alias["net_income"], c);   net_income.append(v)

    dep_cf=[]; capex=[]; chg_wc=[]
    for c in (cf.columns if not cf.empty else cols):
        v,_n,_w = find_value(cf, alias["da"], c);           dep_cf.append(v)
        v,_n,_w = find_value(cf, alias["capex"], c);        capex.append(v)
        v,_n,_w = find_value(cf, alias["change_wc_cf"], c); chg_wc.append(v)

    NWC, delta_nwc, nwc_src = _compute_operating_nwc_arrays(bal, alias)

    # Fallback ΔNWC TTM trimestral
    if (len(delta_nwc)==0) or (np.isnan(delta_nwc[0])):
        try:
            qbal = tk.quarterly_balance_sheet
            if qbal is not None and not qbal.empty and len(qbal.columns) >= 5:
                _NWC_q, _delta_q, _src_q = _compute_operating_nwc_arrays(qbal, alias)
                if len(_NWC_q) >= 5 and not np.isnan(_NWC_q[0]) and not np.isnan(_NWC_q[4]):
                    arr = [np.nan]*(len(bal.columns) if not bal.empty else 1)
                    arr[0] = float(_NWC_q[0] - _NWC_q[4])
                    delta_nwc = np.array(arr, dtype=float)
                    nwc_src = "Quarterly_TTM"
        except Exception:
            pass

    # Fallback desde Cash Flow (signo inverso)
    if (len(delta_nwc)==0) or (np.isnan(delta_nwc[0])):
        if len(chg_wc)>0 and not np.isnan(chg_wc[0]):
            delta_nwc = np.array([-x if not np.isnan(x) else np.nan for x in chg_wc], dtype=float)
            nwc_src = "CF_fallback"

    # D&A: priorizar CashFlow; sino IS; ✅ asegurar POSITIVO
    da=[]
    for i in range(max(len(da_is),len(dep_cf))):
        v_cf = dep_cf[i] if i<len(dep_cf) else np.nan
        v_is = da_is[i] if i<len(da_is) else np.nan
        v = v_cf if not np.isnan(v_cf) else (v_is if not np.isnan(v_is) else np.nan)
        if not np.isnan(v):
            v = abs(float(v))  # <- corrección clave
        da.append(v)

    # Capex como salida de caja
    capex = [abs(v) if not np.isnan(v) else np.nan for v in capex]

    # Series balance relevantes
    def _get_bal_series(key):
        arr=[]
        for c in (bal.columns if not bal.empty else cols):
            v,_,_ = find_value(bal, alias[key], c)
            arr.append(v)
        return arr

    cur_debt   = _get_bal_series("cur_debt")
    lt_debt    = _get_bal_series("lt_debt")
    lease_lt   = _get_bal_series("lease_lt")
    lease_cur  = _get_bal_series("lease_cur")
    total_debt = _get_bal_series("total_debt")
    cash_like  = _get_bal_series("cash_like")
    cash_res   = _get_bal_series("cash_restricted")
    sti        = _get_bal_series("sti")
    equity_tot = _get_bal_series("equity_total")
    ppe_net    = _get_bal_series("ppe_net")

    def nz(x):
        return 0.0 if (x is None or (isinstance(x,float) and np.isnan(x))) else float(x)

    N = len(bal.columns) if not bal.empty else len(cols)
    debt_series=[]
    for i in range(N):
        td = total_debt[i] if i<len(total_debt) and not np.isnan(total_debt[i]) else np.nan
        if np.isnan(td):
            td = nz(cur_debt[i]) + nz(lt_debt[i]) + nz(lease_lt[i]) + nz(lease_cur[i])
        debt_series.append(td)

    # ✅ EFECTIVO: no sumar 'sti' si es financiero-like
    info_tk  = tk.info or {}
    sector_l = (info_tk.get("sector") or "").lower()
    ind_l    = (info_tk.get("industry") or "").lower()
    financial_like = any(s in ind_l for s in ["bank", "insurance", "capital markets", "reit"]) \
                     or any(s in sector_l for s in ["banks", "insurance", "reit"])

    if financial_like:
        cash_series = [ nz(cash_like[i]) + nz(cash_res[i]) for i in range(N) ]
    else:
        cash_series = [ nz(cash_like[i]) + nz(cash_res[i]) + nz(sti[i]) for i in range(N) ]

    eq_series   = [ nz(equity_tot[i]) for i in range(N) ]
    ppe_series  = [ nz(ppe_net[i]) for i in range(N) ]

    def first_valid(arr): return arr[0] if len(arr)>0 else np.nan

    return {
        "years": cols,
        "revenue": revenue, "ebit": ebit, "tax_exp": tax_exp, "interest_exp": int_exp,
        "da": da, "capex": capex, "delta_nwc": list(delta_nwc if isinstance(delta_nwc, np.ndarray) else []),
        "net_income": net_income,
        "cash_last": first_valid(cash_series),
        "debt_total_last": first_valid(debt_series),
        "debt_total_prev": debt_series[1] if len(debt_series)>1 else np.nan,
        "equity_last": first_valid(eq_series),
        "ppe_last": first_valid(ppe_series),
        "nwc_source": nwc_src,
        "inc": inc.copy(), "bal": bal.copy(), "cf": cf.copy(),
        "debt_series": debt_series, "cash_series": cash_series
    }

def collect_all_statements_long(tickers: List[str]) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Devuelve (annual_long, quarterly_long) con columnas: [Ticker, Periodicity, Statement, Date, Account, Value]"""
    rows_a=[]; rows_q=[]
    for t in tickers:
        tk = yf.Ticker(t)
        # Annual
        for st_name, df in [("Income", tk.financials), ("Balance", tk.balance_sheet), ("CashFlow", tk.cashflow)]:
            if isinstance(df, pd.DataFrame) and not df.empty:
                for col in df.columns:
                    for acct, val in df[col].items():
                        rows_a.append({"Ticker": t, "Periodicity": "Annual", "Statement": st_name,
                                       "Date": pd.to_datetime(col), "Account": str(acct),
                                       "Value": float(val) if pd.notna(val) else np.nan})
        # Quarterly
        for st_name, df in [("Income", tk.quarterly_financials), ("Balance", tk.quarterly_balance_sheet), ("CashFlow", tk.quarterly_cashflow)]:
            if isinstance(df, pd.DataFrame) and not df.empty:
                for col in df.columns:
                    for acct, val in df[col].items():
                        rows_q.append({"Ticker": t, "Periodicity": "Quarterly", "Statement": st_name,
                                       "Date": pd.to_datetime(col), "Account": str(acct),
                                       "Value": float(val) if pd.notna(val) else np.nan})
    annual   = pd.DataFrame(rows_a)
    quarterly= pd.DataFrame(rows_q)
    if not annual.empty:   annual   = annual.sort_values(["Ticker","Statement","Date","Account"])
    if not quarterly.empty:quarterly= quarterly.sort_values(["Ticker","Statement","Date","Account"])
    return annual, quarterly

# ==============================================
# Celda 4: RF/ERP + ETR + BETA ROBUSTA
# ==============================================
def get_risk_free_usd() -> Tuple[float,str]:
    # 1) FRED DGS10
    if HAS_PDR:
        try:
            today = datetime.today(); start = today - timedelta(days=400)
            s = pdr.DataReader(FRED_10Y, "fred", start=start, end=today).dropna()
            if len(s) > 0:
                return float(s.iloc[-1,0])/100.0, "FRED:DGS10"
        except Exception:
            pass
    # 2) ^TNX
    try:
        tnx = yf.Ticker(UST10_TICKER).history(period="400d")["Close"].dropna()
        if len(tnx)>0:
            return float(tnx.iloc[-1])/1000.0, "^TNX"
    except Exception:
        pass
    # 3) DEFAULT
    return float(CFG["USD_RF_FALLBACK"]), "DEFAULT"

def blended_erp_usd(rf: float) -> float:
    vals=[]
    for yrs in [5,10,30]:
        try:
            start=(datetime.today()-timedelta(days=yrs*365)).strftime("%Y-%m-%d")
            h = yf.Ticker("SPY").history(start=start, interval="1mo")["Close"].dropna()
            if len(h)>=2:
                dur=(h.index[-1]-h.index[0]).days/365.25
                cagr=(h.iloc[-1]/h.iloc[0])**(1/dur)-1
                vals.append(float(np.clip(cagr-rf, ERP_MIN, ERP_MAX)))
        except Exception:
            pass
    if not vals: return FALLBACK_ERP
    return float(np.mean(vals))

def pct_string_to_float(s: str, default=0.0) -> float:
    t = (s or "").strip().replace("%","").replace(",", ".")
    if t == "": return default
    val = float(t)
    return val/100 if val > 1 else val

def get_rf_erp_with_sources(valuation_ccy: str) -> Tuple[float,float,str,str]:
    c = valuation_ccy.upper()
    if c == "USD":
        rf, rf_src = get_risk_free_usd()
        erp_in = input(f"ERP {c} (Enter=blend ≈ {FALLBACK_ERP:.2%}): ").strip()
        erp = blended_erp_usd(rf) if erp_in == "" else pct_string_to_float(erp_in, FALLBACK_ERP)
        erp = float(np.clip(erp, ERP_MIN, ERP_MAX))
        erp_src = "DEFAULT" if erp_in=="" else "USER"
        return rf, erp, rf_src, erp_src
    # Otras monedas: pedir al usuario y documentar
    rf_in  = input(f"Risk-free en {c} (ej. 0.06 = 6%): ").strip()
    erp_in = input(f"ERP en {c} (ej. 0.07 = 7%): ").strip()
    rf  = pct_string_to_float(rf_in, 0.06)
    erp = pct_string_to_float(erp_in, 0.07)
    return rf, erp, ("USER" if rf_in else "DEFAULT"), ("USER" if erp_in else "DEFAULT")

def compute_annual_etr(tax_series: List[float], ebit_series: List[float], int_series: List[float], country: str) -> Tuple[float, float, str]:
    """
    ETR_t = Tax_t / max(1, EBIT_t - Interest_t)
    Usar mediana últimos 3 años válidos y capear por país.
    Retorna: (ETR_final, ETR_med3, source_tag)
    """
    cap_table = CFG["ETR_CAP_BY_COUNTRY"]
    cap = cap_table.get(country, cap_table.get("_DEFAULT", 0.30))
    etrs = []
    for tax, ebit, inte in zip(tax_series, ebit_series, int_series):
        try:
            ebt = (0.0 if np.isnan(ebit) else float(ebit)) - (0.0 if np.isnan(inte) else float(inte))
            denom = max(1.0, ebt)
            if not np.isnan(tax) and denom > 0:
                etr_t = float(tax)/float(denom)
                if 0.0 <= etr_t <= 1.0:
                    etrs.append(etr_t)
        except Exception:
            pass
    etrs = [x for x in etrs if np.isfinite(x)]
    source = "ETR_3Y_MEDIAN"
    if len(etrs) >= 3:
        med3 = float(np.median(etrs[:3]))
        etr_final = float(min(med3, cap))
        return etr_final, med3, source
    elif len(etrs) >= 1:
        med = float(np.median(etrs))
        etr_final = float(min(med, cap))
        return etr_final, med, "ETR_MEDIAN_PARTIAL"
    else:
        # Default por país
        return cap, cap, "DEFAULT_COUNTRY"

def _winsorize_1_99(x: pd.Series) -> pd.Series:
    if x is None or x.empty: return x
    lo, hi = np.nanpercentile(x, 1), np.nanpercentile(x, 99)
    return x.clip(lower=lo, upper=hi)

def beta_weekly_5y_robust(ticker: str, price_ccy: str, rf_annual: float, years: int=5) -> dict:
    bench = ("SPY" if (price_ccy or "USD").upper() in ("USD","") else
             "^MXX" if (price_ccy or "").upper()=="MXN" else
             "^STOXX50E" if (price_ccy or "").upper()=="EUR" else
             "^FTSE" if (price_ccy or "").upper()=="GBP" else
             "^N225" if (price_ccy or "").upper()=="JPY" else "^ACWI")
    start = (datetime.today() - timedelta(days=years*365+10)).strftime("%Y-%m-%d")
    try:
        data = yf.download([ticker, bench], start=start, interval="1wk", auto_adjust=True, progress=False)
        if isinstance(data.columns, pd.MultiIndex):
            r = data["Close"][ticker].pct_change(fill_method=None).dropna()
            m = data["Close"][bench].pct_change(fill_method=None).dropna()
        else:
            r = data[ticker].pct_change(fill_method=None).dropna()
            m = data[bench].pct_change(fill_method=None).dropna()
        com = r.index.intersection(m.index)
        r, m = r.loc[com], m.loc[com]
        if len(r) < 60:
            return {"beta_calc": 1.0, "R2": 0.0, "N": len(r), "beta_info": np.nan,
                    "beta_used": 1.0, "beta_source": f"default_beta len={len(r)}", "bench": bench}
        r = _winsorize_1_99(r); m = _winsorize_1_99(m)
        rf_w = (rf_annual/52.0)
        ex_r = r - rf_w; ex_m = m - rf_w
        cov = np.cov(ex_r, ex_m)[0,1]; var = np.var(ex_m)
        beta_calc = float(cov/var) if var>0 else 1.0
        corr = np.corrcoef(ex_r, ex_m)[0,1] if var>0 else 0.0
        R2 = float(corr**2) if np.isfinite(corr) else 0.0
        N  = int(len(ex_r))
        # beta_info de yfinance (si disponible)
        info = yf.Ticker(ticker).info or {}
        beta_info = float(info.get("beta")) if info.get("beta") is not None else np.nan
        # Regla determinística
        if (N>=120 and R2>=0.10) and np.isfinite(beta_calc):
            beta_used, src = beta_calc, "CALC"
        elif np.isfinite(beta_info):
            beta_used, src = beta_info, "INFO"
        else:
            beta_used, src = 1.0, "SECTOR_FALLBACK"
        return {"beta_calc": beta_calc, "R2": R2, "N": N, "beta_info": beta_info,
                "beta_used": beta_used, "beta_source": src, "bench": bench}
    except Exception as e:
        return {"beta_calc": 1.0, "R2": 0.0, "N": 0, "beta_info": np.nan,
                "beta_used": 1.0, "beta_source": f"fallback:{e}", "bench": bench}

# ==============================================
# Celda 5: FCFF ROBUSTO + FADE g_exp→g_term
# ==============================================
def robust_fcff0(fields: dict, etr_final: float) -> Tuple[float, dict]:
    """
    FCFF0 = NOPAT0 + D&A_avg - Capex_avg - ΔNWC_avg
    Todos los promedios por defecto en 3 años (si hay 5, permitir 5; si no, TTM_4Q).
    Retorna FCFF0 (en moneda de estados) y dict con promedios y método.
    """
    # series
    ebit    = fields.get("ebit",[]) or []
    da_arr  = fields.get("da",[]) or []
    capex   = fields.get("capex",[]) or []
    dNWC    = fields.get("delta_nwc",[]) or []

    def _clean_numeric(a):
        return [float(x) for x in a if x is not None and np.isfinite(x)]

    da_c   = _clean_numeric(da_arr)
    cap_c  = _clean_numeric(capex)
    dnwc_c = _clean_numeric(dNWC)

    # Elegimos la ventana más robusta disponible: 5 → 3 → 1/TTM
    method = "ANNUAL_3Y_MEAN"
    def _avg_last(a, n):
        return float(np.mean(a[:n])) if len(a)>=n else (float(np.mean(a)) if len(a)>=1 else np.nan)

    # Por diseño priorizo 5 si está disponible
    if len(da_c)>=5 and len(cap_c)>=5 and len(dnwc_c)>=5:
        DA_avg = _avg_last(da_c,5); CAPEX_avg = _avg_last(cap_c,5); DNWC_avg = _avg_last(dnwc_c,5)
        method = "ANNUAL_5Y_MEAN"
    elif len(da_c)>=3 and len(cap_c)>=3 and len(dnwc_c)>=3:
        DA_avg = _avg_last(da_c,3); CAPEX_avg = _avg_last(cap_c,3); DNWC_avg = _avg_last(dnwc_c,3)
        method = "ANNUAL_3Y_MEAN"
    else:
        # Intento TTM simple (ya hicimos fallback arriba al construir ΔNWC)
        DA_avg = _avg_last(da_c,1)
        CAPEX_avg = _avg_last(cap_c,1)
        DNWC_avg  = _avg_last(dnwc_c,1)
        method = "TTM_4Q"  # etiqueta

    ebit0 = first_non_nan(ebit, np.nan)
    if np.isnan(ebit0):
        return np.nan, {"DATA_GAPS": True, "why": "missing EBIT", "ΔNWC_METHOD": method}

    NOPAT0 = float(ebit0) * (1 - float(etr_final))
    for_check = [DA_avg, CAPEX_avg, DNWC_avg]
    if any([np.isnan(x) for x in for_check]):
        return np.nan, {"DATA_GAPS": True, "why": "missing DA/Capex/ΔNWC", "ΔNWC_METHOD": method}

    FCFF0 = float(NOPAT0 + DA_avg - CAPEX_avg - DNWC_avg)
    meta = {"DELTA_NWC_AVG": DNWC_avg, "CAPEX_AVG": CAPEX_avg, "DA_AVG": DA_avg,
            "NOPAT0": NOPAT0, "ΔNWC_METHOD": method, "DATA_GAPS": False}
    return FCFF0, meta

def compute_roic_and_gexp(ebit0, tax_r, ppe_last, operating_nwc_last, reinvestment):
    # CIO ≈ NetPPE + NWC operativo
    CIO0 = float(max(1e-6, (0.0 if np.isnan(ppe_last) else ppe_last) + (0.0 if np.isnan(operating_nwc_last) else operating_nwc_last)))
    NOPAT0 = float(ebit0) * (1 - float(tax_r))
    ROIC0 = float(NOPAT0 / CIO0) if CIO0>0 else np.nan
    b0 = max(0.0, float(reinvestment) / max(1e-6, NOPAT0)) if NOPAT0>0 else 0.0
    g_exp = float(np.clip(b0 * (ROIC0 if not np.isnan(ROIC0) else 0.1), MIN_G_EXPL, MAX_G_EXPL))
    return NOPAT0, ROIC0, b0, g_exp, CIO0

def project_fcff_with_fade(fcff0: float, g_exp: float, g_term: float, h: int, method: str="linear") -> List[float]:
    if method.lower() == "linear":
        gs = [g_exp - (g_exp - g_term) * (t/h) for t in range(1, h+1)]
        fcffs = []
        last = fcff0
        for g in gs:
            last = last*(1+g)
            fcffs.append(last)
        return fcffs
    # H-Model (dividend-intuition adaptada a FCFF)
    H = h/2.0
    # Para H-Model tradicional se usaría una fórmula cerrada en DDM.
    # Aquí devolvemos la senda lineal como aproximación estable si no hay driver adicional.
    gs = [g_exp - (g_exp - g_term) * (t/h) for t in range(1, h+1)]
    fcffs = []
    last = fcff0
    for g in gs:
        last = last*(1+g)
        fcffs.append(last)
    return fcffs

# ==============================================
# Celda 6: PRICE/SHARES + DEUDA BRUTA + DCF INDUSTRIAL (WACC FIX)
# ==============================================
def safe_price_and_shares(tk: yf.Ticker, price_ccy_hint: str):
    """
    Devuelve: px, sh, price_ccy, shares_source(str), currency_check(str: OK/REQUIRED)
    Marca MKTCAP/PX cuando se infiere shares; si eso pasa ⇒ CURRENCY_CHECK = REQUIRED
    """
    info = tk.info or {}
    # Precio
    px = None
    if hasattr(tk,"fast_info") and tk.fast_info.get("lastPrice") is not None:
        px = float(tk.fast_info["lastPrice"])
    else:
        rawp = info.get("currentPrice") or info.get("previousClose")
        if rawp is not None:
            px = float(rawp)
    if px is None or (isinstance(px,float) and np.isnan(px)):
        try:
            h = tk.history(period="5d")["Close"].dropna()
            if len(h)>0: px = float(h.iloc[-1])
        except Exception:
            pass
    price_ccy = (info.get("currency") or price_ccy_hint or "USD").upper()
    price_ccy, _, px = normalize_price_currency(price_ccy, None, px)

    # Acciones
    shares_source = "INFO.sharesOutstanding"
    sh = info.get("sharesOutstanding") or info.get("floatShares") or info.get("impliedSharesOutstanding")
    if (sh is None or (isinstance(sh,(float,int)) and (np.isnan(sh) or sh<=0))) and hasattr(tk,"get_shares"):
        try:
            gs = tk.get_shares()
            if isinstance(gs, pd.DataFrame) and not gs.empty:
                if "Diluted" in gs:
                    sh = float(gs["Diluted"].dropna().iloc[-1]); shares_source = "get_shares.Diluted"
                elif "Basic" in gs:
                    sh = float(gs["Basic"].dropna().iloc[-1]);   shares_source = "get_shares.Basic"
        except Exception:
            pass
    if (sh is None or (isinstance(sh,float) and (np.isnan(sh) or sh<=0))) and (info.get("marketCap") and px and px>0):
        sh = float(info["marketCap"])/float(px)
        shares_source = "MKTCAP/PX"
    if sh is None or (isinstance(sh,float) and (np.isnan(sh) or sh<=0)) or px is None or (isinstance(px,float) and np.isnan(px)):
        return np.nan, np.nan, price_ccy, "MISSING", "REQUIRED"
    currency_check = "REQUIRED" if shares_source=="MKTCAP/PX" else "OK"
    return float(px), float(sh), price_ccy, shares_source, currency_check

def compute_gross_debt(fields: dict) -> float:
    """
    Deuda bruta = current debt + long-term debt + lease liabilities (cuando no hay total_debt).
    Usamos el último año disponible (ya compuesto en extract_time_series_v4).
    """
    debt_last = fields.get("debt_total_last", np.nan)
    return 0.0 if np.isnan(debt_last) else float(debt_last)

def compute_dcf_industrial(
    tk: yf.Ticker,
    fields: dict,
    price_ccy: str,
    valuation_ccy: str,
    rf: float, erp: float,
    rf_src: str, erp_src: str,
    fade_h: int = YEARS_PROJ,
    fade_method: str = CFG["FADE_METHOD"]
):
    info = tk.info or {}
    fin_ccy = (info.get("financialCurrency") or valuation_ccy).upper()
    country = (info.get("country") or "").strip() or "_DEFAULT"

    # Precio y acciones (con fuentes)
    px, sh, price_ccy, shares_source, curr_check = safe_price_and_shares(tk, price_ccy)
    if np.isnan(px) or np.isnan(sh) or sh<=0:
        return np.nan, {"hard_error": "no price/shares"}, np.nan, "no_price_or_shares"

    # ETR anual mediana 3y con cap país
    etr_final, etr_med, etr_source = compute_annual_etr(
        fields.get("tax_exp",[]), fields.get("ebit",[]), fields.get("interest_exp",[]), country
    )

    # FCFF0 robusto (EN moneda de estados)
    FCFF0_fin, fcff_meta = robust_fcff0(fields, etr_final)

    # FX spot a moneda de valoración
    spot = fx_spot(fin_ccy, valuation_ccy)
    FCFF0_val = FCFF0_fin * spot if np.isfinite(FCFF0_fin) else np.nan

    # Beta robusta semanal 5y (regla determinística)
    beta_pack = beta_weekly_5y_robust(tk.ticker, price_ccy, rf)
    beta_used = float(beta_pack["beta_used"])
    beta_src  = beta_pack["beta_source"]

    # Costos de capital
    Re = float(rf + beta_used*erp)

    # g_term por macro y moneda
    cc = valuation_ccy.upper()
    if cc in ("USD","EUR"): g_lo,g_hi = GTERM_DEV.get(cc,(0.015,0.025))
    else:                   g_lo,g_hi = GTERM_EM
    g_term = min(g_hi, Re - 0.01) if Re>0.01 else g_lo

    # g_exp vía ROIC/reinversión (opcionalmente, si tenemos ppe y NWC operativo)
    ebit0 = first_non_nan(fields.get("ebit",[]), np.nan)
    operating_nwc_last = np.nan
    try:
        bal = fields.get("bal", pd.DataFrame()); alias = load_alias_builtin()
        if bal is not None and not bal.empty:
            NWC, _, _ = _compute_operating_nwc_arrays(bal, alias)
            if len(NWC)>0 and not np.isnan(NWC[0]): operating_nwc_last = float(NWC[0])
    except Exception:
        pass
    capex0 = first_non_nan(fields.get("capex",[]), 0.0)
    da0    = first_non_nan(fields.get("da",[]), 0.0)
    dNWC0  = first_non_nan(fields.get("delta_nwc",[]), 0.0)
    reinv_fin = (0.0 if np.isnan(capex0) else capex0) - (0.0 if np.isnan(da0) else da0) + (0.0 if np.isnan(dNWC0) else dNWC0)

    _, ROIC0, b0, g_exp_raw, CIO0 = compute_roic_and_gexp(
        ebit0, etr_final, fields.get("ppe_last", np.nan), operating_nwc_last, reinv_fin
    )
    g_exp = float(np.clip(g_exp_raw, MIN_G_EXPL, MAX_G_EXPL))

    # Proyección con fade
    if not np.isfinite(FCFF0_val):
        return np.nan, {"hard_error": "no FCFF0"}, px, "GateA_fail"
    fcffs = project_fcff_with_fade(FCFF0_val, g_exp, g_term, fade_h, method=fade_method)

    # Estructura de capital observada (deuda BRUTA en los PESOS del WACC)
    px_val = px * fx_spot(price_ccy, valuation_ccy)
    E_mkt  = max(px_val * sh, 0.0)

    D_gross = compute_gross_debt(fields) * spot    # deuda bruta en moneda de valoración
    Cash_c  = (0.0 if np.isnan(fields.get("cash_last", np.nan)) else float(fields.get("cash_last"))) * spot

    # Rd efectivo aproximado: interés/ deuda promedio (deuda bruta)
    debt_last = fields.get("debt_total_last", np.nan)
    debt_prev = fields.get("debt_total_prev", np.nan)
    int0      = first_non_nan(fields.get("interest_exp",[]), np.nan)
    if np.isnan(int0) or (np.isnan(debt_last) and np.isnan(debt_prev)) or (max(1e-6, (0.0 if np.isnan(debt_last) else debt_last) + (0.0 if np.isnan(debt_prev) else debt_prev))<=0):
        Rd = max(rf, 0.05); kd_src="Rd_fallback"
    else:
        avg_debt = 0.5*((0.0 if np.isnan(debt_last) else float(debt_last)) + (0.0 if np.isnan(debt_prev) else float(debt_prev)))
        Rd = float(np.clip(abs(float(int0)) / max(1e-6, avg_debt), rf, 0.25))
        kd_src="interest/avgDebt"
    Rd_eff = Rd*(1.0 - etr_final)

    V = float(E_mkt + D_gross)
    if V>0:
        wE = E_mkt / V; wD = D_gross / V
        WACC = wE*Re + wD*Rd_eff
    else:
        WACC = Re

    # Validación g_term < WACC (si no, recortar g_term)
    if WACC <= g_term + 1e-4:
        g_term = max(min(g_term, WACC-0.01), -0.20)

    # Valuación: PV de explícitos + TV Gordon en t=h
    PV = sum(fc/((1+WACC)**i) for i,fc in enumerate(fcffs,1))
    TV = fcffs[-1]*(1+g_term)/(WACC-g_term)
    EV = PV + TV/((1+WACC)**fade_h)

    # Puente EV → Equity (ahora sí usa Net Debt)
    net_debt = D_gross - Cash_c
    equity_value = EV - net_debt
    intrinsic_val_ps_valccy = equity_value / sh
    intrinsic_px_price_ccy = intrinsic_val_ps_valccy * (fx_spot(valuation_ccy, price_ccy) if valuation_ccy!=price_ccy else 1.0)

    meta = dict(
        fin_ccy=fin_ccy, price_ccy=price_ccy, valuation_ccy=valuation_ccy,
        rf=rf, erp=erp, rf_source=rf_src, erp_source=erp_src,
        beta_calc=beta_pack["beta_calc"], beta_info=beta_pack["beta_info"], beta_used=beta_used,
        beta_R2=beta_pack["R2"], beta_N=beta_pack["N"], beta_source=beta_src,
        Re=Re, Rd=Rd, Rd_eff=Rd_eff, tax_rate=etr_final, ETR_3Y_MEDIAN=etr_med, ETR_SOURCE=etr_source,
        WACC=WACC, WACC_NET_DEBT=False, g_exp=g_exp, g_term=g_term, FCFF0=FCFF0_val,
        E=E_mkt, D_gross=D_gross, Cash=Cash_c,
        DATA_GAPS=bool(fcff_meta.get("DATA_GAPS", False)),
        DELTA_NWC_AVG=fcff_meta.get("DELTA_NWC_AVG", np.nan),
        CAPEX_AVG=fcff_meta.get("CAPEX_AVG", np.nan),
        DA_AVG=fcff_meta.get("DA_AVG", np.nan),
        ΔNWC_METHOD=fcff_meta.get("ΔNWC_METHOD",""),
        SHARES_SOURCE=shares_source, CURRENCY_CHECK=curr_check,
        assumptions=f"Fade={fade_method} h={fade_h}; WACC pesos con DEUDA BRUTA; EV→Equity con NET DEBT"
    )
    return intrinsic_px_price_ccy, meta, px, "DCF_Industrial_OK"

# ==============================================
# Celda 7: FINANCIALS (DDM/Excess Returns) + ETF/ÍNDICES (CORREGIDA)
# ==============================================
def dividend_ttm(tk: yf.Ticker, current_price: float) -> Tuple[float,float]:
    div_ttm = 0.0
    try:
        divs = tk.dividends
        if isinstance(divs, pd.Series) and not divs.empty:
            cutoff = datetime.today() - timedelta(days=365)
            div_ttm = float(divs[divs.index >= cutoff].sum())
    except Exception:
        pass
    info = tk.info or {}
    if (div_ttm == 0.0) and (info.get("dividendRate") is not None):
        try: div_ttm = float(info.get("dividendRate"))
        except Exception: pass
    yld = (div_ttm/current_price) if (current_price and current_price>0) else np.nan
    if yld and yld > 1.5: yld = yld/100.0
    return div_ttm, yld

def ddm_2stage(div_ttm_ps: float, Re: float, g_exp: float, g_term: float, years: int=YEARS_PROJ) -> float:
    if div_ttm_ps <= 0 or Re <= g_term+1e-4: return np.nan
    pv = 0.0
    for t in range(1, years+1):
        Dt = div_ttm_ps * ((1+g_exp)**t)
        pv += Dt / ((1+Re)**t)
    Dn = div_ttm_ps * ((1+g_exp)**years)
    TV = Dn*(1+g_term)/(Re-g_term)
    return float(pv + TV/((1+Re)**years))

def compute_financials_models(
    tk: yf.Ticker, price_ccy: str, valuation_ccy: str, rf: float, erp: float,
    rf_src: str, erp_src: str, alias: dict
):
    info = tk.info or {}
    fin_ccy = (info.get("financialCurrency") or valuation_ccy).upper()

    px, sh, price_ccy, shares_source, curr_check = safe_price_and_shares(tk, price_ccy)
    if np.isnan(px) or np.isnan(sh) or sh<=0:
        return np.nan, {"hard_error": "no price/shares"}, np.nan, "FIN_no_price_or_shares"

    # Beta usada para Re (consistente con industrial)
    beta_pack = beta_weekly_5y_robust(tk.ticker, price_ccy, rf)
    beta_used = float(beta_pack["beta_used"]); beta_src  = beta_pack["beta_source"]
    Re = rf + beta_used*erp

    # DDM 2-etapas si hay dividendos
    div_ttm, _ = dividend_ttm(tk, px)
    cc = valuation_ccy.upper()
    if cc in ("USD","EUR"): g_lo,g_hi = GTERM_DEV.get(cc,(0.015,0.025))
    else:                   g_lo,g_hi = GTERM_EM
    g_term = min(g_hi, Re-0.01) if Re>0.01 else g_lo
    g_exp  = min(0.06, Re-0.015)

    val_ps_val = ddm_2stage(div_ttm, Re, g_exp, g_term, YEARS_PROJ) if div_ttm>0 else np.nan

    # Fallback: Exceso de retornos si DDM no aplica
    if np.isnan(val_ps_val):
        fields = extract_time_series_v4(tk, 5, alias)
        spot = fx_spot((info.get("financialCurrency") or valuation_ccy), valuation_ccy)
        eq_last = fields.get("equity_last", np.nan)
        ni0     = first_non_nan(fields.get("net_income",[]))
        BVPS_val = (eq_last/sh)*spot if (not np.isnan(eq_last) and sh>0) else np.nan
        if np.isnan(BVPS_val) or BVPS_val<=0:
            # ✅ Fallback final a DCF industrial
            fields = extract_time_series_v4(tk, 6, alias)
            return compute_dcf_industrial(tk, fields, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src)

        eq_prev = np.nan
        bal = fields.get("bal", pd.DataFrame())
        if bal is not None and not bal.empty and bal.shape[1] >= 2:
            e0,_,_ = find_value(bal, load_alias_builtin()["equity_total"], bal.columns[0])
            e1,_,_ = find_value(bal, load_alias_builtin()["equity_total"], bal.columns[1])
            eq_last = e0 if not np.isnan(e0) else eq_last
            eq_prev = e1
        ROE = np.nan
        if not np.isnan(ni0) and not np.isnan(eq_last) and eq_last>0:
            eq_avg = eq_last if np.isnan(eq_prev) else (eq_last+eq_prev)/2.0
            if eq_avg>0: ROE = float(ni0/eq_avg)
        if np.isnan(ROE): ROE = 0.12

        payout = 0.0
        try:
            if (not np.isnan(ni0)) and ni0>0 and div_ttm>0:
                payout = max(0.0, min(1.0, (div_ttm*sh)/ni0))
        except Exception:
            pass
        b = 1.0 - payout
        g_exp = float(np.clip(b*ROE, MIN_G_EXPL, MAX_G_EXPL))
        # PV de residuales + valor terminal
        residuals_pv = 0.0
        for t in range(1, YEARS_PROJ+1):
            residual_t = (ROE - Re) * (BVPS_val * (b**(t-1)))
            residuals_pv += residual_t / ((1+Re)**t)
        BVN  = BVPS_val * (b**YEARS_PROJ)
        term = ((ROE - Re) * BVN) * (1+g_term) / (((1+Re)**YEARS_PROJ) * (Re - g_term)) if Re>g_term+1e-4 else 0.0
        val_ps_val = BVPS_val + residuals_pv + term

    # ✅ Si aún no hay valor, fallback a DCF industrial
    if np.isnan(val_ps_val):
        fields = extract_time_series_v4(tk, 6, alias)
        return compute_dcf_industrial(tk, fields, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src)

    intrinsic_px_price_ccy = val_ps_val * (fx_spot(valuation_ccy, price_ccy) if valuation_ccy!=price_ccy else 1.0)
    meta = dict(
        fin_ccy=fin_ccy, price_ccy=price_ccy, valuation_ccy=valuation_ccy,
        rf=rf, erp=erp, rf_source=rf_src, erp_source=erp_src,
        Re=Re, Rd=np.nan, Rd_eff=np.nan, tax_rate=np.nan, WACC=Re,
        beta_calc=beta_pack["beta_calc"], beta_info=beta_pack["beta_info"], beta_used=float(beta_used),
        beta_R2=beta_pack["R2"], beta_N=beta_pack["N"], beta_source=beta_src,
        g_exp=g_exp, g_term=g_term, FCFF0=np.nan, E=np.nan, D_gross=np.nan, Cash=np.nan,
        DATA_GAPS=False, SHARES_SOURCE=shares_source, CURRENCY_CHECK=curr_check,
        assumptions="Financials: DDM/Excess-Returns; FX spot; β semanal robusta con fallback a DCF industrial"
    )
    return intrinsic_px_price_ccy, meta, px, "FIN_OK"

def compute_etf_index_intrinsic(tk: yf.Ticker, price_ccy: str, valuation_ccy: str, rf: float, erp: float, rf_src: str, erp_src: str):
    info = tk.info or {}
    px = None
    if hasattr(tk,"fast_info") and tk.fast_info.get("lastPrice") is not None:
        px = float(tk.fast_info["lastPrice"])
    else:
        rawp = info.get("currentPrice") or info.get("previousClose")
        if rawp is not None: px = float(rawp)
    if px is None or (isinstance(px,float) and np.isnan(px)):
        h = tk.history(period="5d")["Close"].dropna()
        px = float(h.iloc[-1]) if len(h)>0 else np.nan
    price_ccy, _, px = normalize_price_currency((info.get("currency") or price_ccy).upper(), None, px)

    over_ratio = 1.50
    intrinsic_px = px/over_ratio if (px and px>0) else np.nan
    # β para informar Re CAPM
    beta_pack = beta_weekly_5y_robust(tk.ticker, price_ccy, rf)
    Re = rf + beta_pack["beta_used"]*erp

    meta = dict(
        fin_ccy=(info.get("financialCurrency") or price_ccy), price_ccy=price_ccy, valuation_ccy=valuation_ccy,
        rf=rf, erp=erp, rf_source=rf_src, erp_source=erp_src,
        Re=Re, Rd=Re, Rd_eff=np.nan, tax_rate=np.nan, WACC=Re,
        beta_calc=beta_pack["beta_calc"], beta_info=beta_pack["beta_info"], beta_used=float(beta_pack["beta_used"]),
        beta_R2=beta_pack["R2"], beta_N=beta_pack["N"], beta_source=f"calc_vs_bench",
        g_exp=np.nan, g_term=np.nan, FCFF0=np.nan, E=np.nan, D_gross=np.nan, Cash=np.nan,
        DATA_GAPS=False, SHARES_SOURCE="N/A", CURRENCY_CHECK="OK",
        assumptions="ETF/INDEX: proxy intrínseco px/1.5; reporte CAPM para referencia"
    )
    return intrinsic_px, meta, px, "ETF_INDEX_DEFAULT"

# ==============================================
# Celda 8: OPTIMIZACIÓN + µ AJUSTADO + EXCEL (CORREGIDA)
# ==============================================
def _parse_tickers(raw: str):
    arr = [sanitize_symbol(t) for t in raw.split(",") if str(t).strip()]
    out=[CANONICAL_TICKERS.get(t, t) for t in arr]
    known_suffixes={'MX','TO','SA','L','PA','HK','SW','SS','SZ','AX','F','DE','MI','AS','VI','HE','CO','JK','NZ','TW'}
    out=[t.replace(".", "-") if "." in t and t.split(".")[-1] not in known_suffixes else t for t in out]
    return list(dict.fromkeys(out))

def is_etf_or_index(sym: str, info: dict) -> bool:
    qt = str((info or {}).get("quoteType") or "").upper()
    if qt in {"ETF","INDEX","MUTUALFUND","FUND"}: return True
    if sym.startswith("^"): return True
    ln = str((info or {}).get("longName") or ""); sn = str((info or {}).get("shortName") or "")
    return ("ETF" in ln.upper()) or ("ETF" in sn.upper())

def align_mu_sigma(val_df: pd.DataFrame, cov_ann: pd.DataFrame, ordered_tickers: List[str], mu_col="MU_ADJ") -> Tuple[np.ndarray,np.ndarray,List[str]]:
    v = val_df.set_index("Ticker")
    v = v[np.isfinite(v[mu_col])].copy()
    inter = [t for t in ordered_tickers if t in v.index and t in cov_ann.index]
    if len(inter)<2:
        raise RuntimeError("No hay suficientes tickers comunes entre valuación y covarianza.")
    v = v.loc[inter]
    mu = v[mu_col].astype(float).values
    Sigma = cov_ann.loc[inter, inter].values
    # Ridge mínimo para PSD
    try: np.linalg.cholesky(Sigma)
    except np.linalg.LinAlgError: Sigma = Sigma + np.eye(Sigma.shape[0])*1e-8
    return mu, Sigma, inter

def max_sharpe_with_sigma_cap(mu: np.ndarray, Sigma: np.ndarray, rf: float, sigma_cap: float, bounds=None) -> np.ndarray:
    n=len(mu)
    bounds = bounds or [(0.0,1.0)]*n
    cons=[{'type':'eq','fun': lambda w: np.sum(w)-1.0}]
    if sigma_cap and sigma_cap>0:
        cons.append({'type':'ineq','fun': lambda w: sigma_cap - np.sqrt(w @ Sigma @ w)})
    w0=np.array([ (low+high)/2 for (low,high) in bounds ], dtype=float)
    def neg_sharpe(w):
        ret=float(w @ mu); vol=float(np.sqrt(w @ Sigma @ w))
        return -((ret-rf)/vol) if vol>0 else 1e9
    res=minimize(neg_sharpe, w0, method="SLSQP", bounds=bounds, constraints=cons, options=dict(maxiter=600))
    w=np.clip(res.x if res.success else w0, 0, 1); s=w.sum()
    return w/s if s>0 else np.ones(n)/n

def main():
    alias = load_alias_builtin()
    default_list = ["AAPL","MSFT","GOOGL","NVDA","META","TSLA","SPY"]
    raw = input(f"Tickers separados por coma {default_list}: ").strip()
    universe = _parse_tickers(raw) if raw else default_list[:]
    if "SPY" not in universe: universe.append("SPY")

    valuation_ccy = (input("Moneda de VALORACIÓN (USD/MXN/EUR...) [USD]: ").strip().upper() or "USD")
    rf, erp, rf_src, erp_src = get_rf_erp_with_sources(valuation_ccy)
    years_hist = int(input("Años históricos para Σ/β (2-10) [5]: ").strip() or "5")
    risk_mult = float(input("¿Cuántos SPY de riesgo máximo? (σ^2 cap = mult × Var(SPY)) [1.0]: ").strip() or "1.0")
    budget_min = float(input("Inversión mínima (en MONEDA BASE) [10000]: ").strip() or "10000")
    budget_max = float(input("Inversión máxima (en MONEDA BASE) [50000]: ").strip() or "50000")
    thresh_na_ratio = float(input(f"Umbral % precios válidos por ticker (0.5-0.95) [0.70]: ").strip() or "0.70")
    LAMBDA = float(input(f"LAMBDA para MU_ADJ (0-1) [{CFG['LAMBDA']}]: ").strip() or str(CFG["LAMBDA"]))

    # Pesos fijos (opcional)
    fixed_weights = {}
    json_fw = input("Pega JSON de weights fijos (ej: {'AAPL':0.2,'MSFT':0.1}) o Enter: ").strip()
    if json_fw:
        try:
            fw = json.loads(json_fw.replace("'", '"'))
            for k,v in fw.items():
                if k in universe:
                    fixed_weights[k] = float(v)
            print("Pesos fijos por JSON:", fixed_weights)
        except Exception as e:
            print("JSON inválido; se ignora. Error:", e)

    dcf_rows=[]; info_rows=[]; fx_meta_rows=[]; rows_port=[]

    # ==== Valuación por ticker (ruteo CORREGIDO) ====
    for sym in universe:
        try:
            tk = yf.Ticker(sym)
            info = tk.info or {}
            price_ccy = (info.get("currency") or valuation_ccy).upper()
            price_ccy, _, _ = normalize_price_currency(price_ccy, None, None)
            sector_l  = (info.get("sector") or "").lower()
            industry_l= (info.get("industry") or "").lower()
            fund      = is_etf_or_index(sym, info)

            # Detectar sólo bancos/seguros/REIT como "financials"
            is_bank_insurer_reit = any(x in industry_l for x in ["bank", "insurance", "reit"]) \
                                   or any(x in sector_l for x in ["banks", "insurance", "reit"])

            # Overrides explícitos: Berkshire y Coinbase por DCF industrial
            if sym in {"BRK-A", "BRK-B", "COIN"}:
                is_bank_insurer_reit = False

            if fund:
                intrinsic, meta, market_px, note = compute_etf_index_intrinsic(
                    tk, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src
                )
            else:
                fields = extract_time_series_v4(tk, 6, alias)
                if is_bank_insurer_reit:
                    intrinsic, meta, market_px, note = compute_financials_models(
                        tk, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src, alias
                    )
                else:
                    intrinsic, meta, market_px, note = compute_dcf_industrial(
                        tk, fields, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src,
                        fade_h=YEARS_PROJ, fade_method=CFG["FADE_METHOD"]
                    )

            if np.isnan(intrinsic) or np.isnan(market_px):
                log.warning(f"{sym}: sin precio intrínseco/mercado válido → omitido")
                continue

            # Dividendos y extremos 5y
            div_ttm, div_y = dividend_ttm(tk, market_px)
            try:
                hist = tk.history(period="5y", auto_adjust=True)["Close"].dropna()
                price_ccy, hist , _ = normalize_price_currency(price_ccy, hist, None)
                max5 = float(hist.max()) if not hist.empty else np.nan
                min5 = float(hist.min()) if not hist.empty else np.nan
            except Exception:
                max5=min5=np.nan
            ptomax = (market_px/max5) if (max5 and max5>0) else np.nan
            ptomin = (market_px/min5) if (min5 and min5>0) else np.nan
            over_ratio = (market_px/intrinsic) if (market_px and intrinsic and intrinsic>0) else np.nan

            # Señal DCF → expected returns
            alpha_dcf = np.nan
            try:
                alpha_dcf = (intrinsic/market_px) - 1.0 if (intrinsic and market_px and market_px>0) else np.nan
            except Exception:
                pass

            dcf_rows.append({
                "Ticker": sym, "IsFundOrIndex": fund,
                "Price": market_px, "PriceCCY": price_ccy,
                "IntrinsicPrice_in_PriceCCY": intrinsic, "OverValRatio": over_ratio,
                "Price_to_Max": ptomax, "Price_to_Min": ptomin,
                "Div_TTM_per_share": div_ttm, "Dividend_Yield": div_y,
                "Beta_Calc": meta.get("beta_calc", np.nan), "Beta_Info": meta.get("beta_info", np.nan),
                "Beta_Used": meta.get("beta_used", np.nan), "BETA_R2": meta.get("beta_R2", np.nan),
                "BETA_N": meta.get("beta_N", np.nan), "BETA_SOURCE": meta.get("beta_source",""),
                "Return_CAPM": meta.get("Re", np.nan),  # µ de CAPM puro
                "WACC": meta.get("WACC", np.nan), "Kd": meta.get("Rd", np.nan),
                "Kd_eff": meta.get("Rd_eff", np.nan), "TaxRate": meta.get("tax_rate", np.nan),
                "ETR_3Y_MEDIAN": meta.get("ETR_3Y_MEDIAN", np.nan),
                "ETR_SOURCE": meta.get("ETR_SOURCE",""),
                "g_exp": meta.get("g_exp", np.nan), "g_term": meta.get("g_term", np.nan),
                "FCFF0_in_valCCY": meta.get("FCFF0", np.nan),
                "ValuationCCY": meta["valuation_ccy"], "FinancialCCY": meta["fin_ccy"],
                "RF": meta["rf"], "ERP": meta["erp"], "RF_SOURCE": meta.get("rf_source",""), "ERP_SOURCE": meta.get("erp_source",""),
                "E_val": meta.get("E", np.nan), "D_gross_val": meta.get("D_gross", np.nan), "Cash_val": meta.get("Cash", np.nan),
                "DATA_GAPS": meta.get("DATA_GAPS", False), "ΔNWC_METHOD": meta.get("ΔNWC_METHOD",""),
                "WACC_NET_DEBT?": meta.get("WACC_NET_DEBT", False),
                "SHARES_SOURCE": meta.get("SHARES_SOURCE",""), "CURRENCY_CHECK": meta.get("CURRENCY_CHECK","OK"),
                "Assumptions": meta.get("assumptions",""), "DCF_ALPHA_raw": alpha_dcf
            })

            info_rows.append({
                "Ticker": sym, "Precio_real": market_px, "SharesSource": meta.get("SHARES_SOURCE",""),
                "CurrencyCheck": meta.get("CURRENCY_CHECK","OK"),
                "FinancialCCY": meta["fin_ccy"], "PriceCCY": price_ccy,
                "Max_5Y": max5, "Min_5Y": min5, "Price_to_Max": ptomax, "Price_to_Min": ptomin,
                "Div_TTM_per_share": div_ttm, "Dividend_Yield": div_y
            })

            fx_meta_rows.append({
                "Ticker": sym, "FinancialCCY": meta["fin_ccy"], "ValuationCCY": valuation_ccy,
                "PriceCCY_norm": price_ccy,
                "FX_spot(fin→val)": fx_spot(meta["fin_ccy"], valuation_ccy),
                "FX_spot(val→price)": fx_spot(valuation_ccy, price_ccy),
                "Beta_Source": meta.get("beta_source","")
            })
        except Exception as e:
            log.warning(f"Ticker {sym}: {e}")

    val_df = pd.DataFrame(dcf_rows).dropna(subset=["IntrinsicPrice_in_PriceCCY","Price"])
    if val_df.empty:
        raise RuntimeError("Ningún ticker con valoración válida.")

    # Clip robusto para alpha_DCF p5–p95
    if "DCF_ALPHA_raw" in val_df.columns:
        al = val_df["DCF_ALPHA_raw"].astype(float)
        if al.notna().sum()>=5:
            lo, hi = np.nanpercentile(al, 5), np.nanpercentile(al, 95)
            val_df["DCF_ALPHA"] = al.clip(lower=lo, upper=hi)
        else:
            val_df["DCF_ALPHA"] = al
    else:
        val_df["DCF_ALPHA"] = np.nan

    val_df["MU_CAPM"] = val_df["Return_CAPM"].astype(float)
    val_df["MU_ADJ"]  = val_df["MU_CAPM"] + LAMBDA*val_df["DCF_ALPHA"].fillna(0.0)
    val_df["LAMBDA"]  = LAMBDA

    # ====== Precios históricos para Σ ======
    start = (datetime.today() - timedelta(days=years_hist*365+10)).strftime("%Y-%m-%d")
    tickers_px = list(dict.fromkeys(val_df["Ticker"].tolist() + ["SPY"]))
    px_all = yf.download(tickers_px, start=start, auto_adjust=True, progress=False, group_by="ticker")
    if px_all.empty: raise RuntimeError("Precios vacíos.")

    if isinstance(px_all.columns, pd.MultiIndex):
        px_close_local = px_all.xs("Close", level=1, axis=1)
    else:
        one = val_df["Ticker"].tolist()[0]
        px_close_local = px_all["Close"].to_frame(name=one) if "Close" in px_all.columns else None
    if px_close_local is None or px_close_local.empty:
        raise RuntimeError("No se obtuvo 'Close'.")

    def to_base_series(sym, ser):
        p_ccy = (yf.Ticker(sym).info or {}).get("currency") or valuation_ccy
        p_ccy, ser, _ = normalize_price_currency(p_ccy, ser, None)
        if p_ccy != valuation_ccy:
            fx_ser = get_fx_series(p_ccy, valuation_ccy, start).reindex(ser.index, method="ffill").fillna(method="bfill")
            return (ser * fx_ser).dropna()
        return ser

    px_close_base = pd.DataFrame(index=px_close_local.index)
    for sym in px_close_local.columns:
        ser = px_close_local[sym].dropna()
        if ser is not None and len(ser)>0:
            px_close_base[sym] = to_base_series(sym, ser)

    thresh = int(round(len(px_close_base) * thresh_na_ratio))
    px_close_base = px_close_base.dropna(thresh=thresh, axis=1).dropna(how="all")
    present = [t for t in px_close_base.columns if t in val_df["Ticker"].tolist()]
    px_close_base = px_close_base[present]
    if px_close_base.shape[1] < 2:
        raise RuntimeError("Quedaron <2 tickers válidos.")

    ret_d   = px_close_base.pct_change(fill_method=None).dropna()
    cov_ann = ret_d.cov()*252
    # === Desv. est. anual por ticker (σ anual en base) → agregar a DCF_VALUATION ===
    vol_ann = pd.Series(np.sqrt(np.diag(cov_ann)), index=cov_ann.index, name="DesvEst_Anual")
    # Mapeamos al dataframe de valuación por 'Ticker'
    val_df["DesvEst_Anual"] = val_df["Ticker"].map(vol_ann).astype(float)

    var_spy = float(cov_ann.loc["SPY","SPY"]) if "SPY" in cov_ann.index else float(np.nanmean(np.diag(cov_ann.values)))
    sigma_cap = math.sqrt(var_spy * risk_mult) if not np.isnan(var_spy) else None
    ordered   = list(px_close_base.columns)

    mu, Sigma, common = align_mu_sigma(val_df, cov_ann, ordered, mu_col="MU_ADJ")

    # Construir bounds con pesos fijos
    bounds = []
    for t in common:
        if t in fixed_weights:
            wfix = max(0.0, min(1.0, float(fixed_weights[t])))
            bounds.append((wfix, wfix))
        else:
            bounds.append((0.0, 1.0))

    # Optimización Max Sharpe con tope de σ
    w = max_sharpe_with_sigma_cap(mu, Sigma, rf, sigma_cap, bounds=bounds)
    weights = pd.Series(w, index=common, name="Weight").sort_values(ascending=False)

    last_px_base = px_close_base[common].ffill().iloc[-1]
    qty = (weights * budget_max) / last_px_base
    qty = np.floor(qty).astype(int)
    qty = np.where((weights.values > 0) & (qty == 0), 1, qty)
    cost_base = float((qty * last_px_base.loc[weights.index].values).sum())
    if cost_base < budget_min or cost_base > budget_max:
        factor = min(1.0, budget_max/max(cost_base,1e-9))
        qty = np.floor(qty * factor).astype(int)
        cost_base = float((qty * last_px_base.loc[weights.index].values).sum())

    w_vec   = weights.values
    port_ret= float(w_vec @ mu)
    port_vol= float(np.sqrt(w_vec @ cov_ann.loc[common,common].values @ w_vec))
    sharpe  = (port_ret - rf)/port_vol if port_vol>0 else np.nan
    last_px_local = px_close_local[common].ffill().iloc[-1]

    rows_port=[]
    for i,t in enumerate(common):
        p_ccy = (yf.Ticker(t).info or {}).get("currency") or valuation_ccy
        p_ccy, _, _ = normalize_price_currency(p_ccy, None, None)
        rows_port.append({
            "Ticker": t, "Weight": float(weights[t]),
            "LastPrice_Local": float(last_px_local[t]), "PriceCCY": p_ccy,
            "FX_PriceCCY_to_Base": fx_spot(p_ccy, valuation_ccy),
            "LastPrice_Base": float(last_px_base[t]),
            "Qty": int(qty[i]), "Position_Base": float(qty[i]*last_px_base[t]),
        })
    port_df = pd.DataFrame(rows_port)

    # Recolectar TODOS los estados (anual / trimestral)
    all_a, all_q = collect_all_statements_long(common)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    outfile = f"{ts}_{XL_OUT}"
    with pd.ExcelWriter(outfile, engine="xlsxwriter", datetime_format="yyyy-mm-dd") as wri:
        # === Reporte principal ===
        pd.DataFrame(info_rows).to_excel(wri, sheet_name="INFO_ACCIONES", index=False)
        pd.DataFrame(fx_meta_rows).to_excel(wri, sheet_name="FX_APLICADO", index=False)
        val_df.to_excel(wri, sheet_name="DCF_VALUATION", index=False)
        port_df.to_excel(wri, sheet_name="PORTFOLIO_BASE", index=False)
        pd.DataFrame({
            "Sharpe":[sharpe], "Port_Ret":[port_ret], "Port_Vol":[port_vol], "RiskFree":[rf], "ERP":[erp],
            "SigmaCap(SPY)":[sigma_cap], "Var(SPY)_Base":[var_spy],
            "ValuationCCY(Base)":[valuation_ccy], "BudgetMin_Base":[budget_min], "BudgetMax_Base":[budget_max]
        }).to_excel(wri, sheet_name="SUMMARY", index=False)
        pd.DataFrame(cov_ann.loc[common, common]).to_excel(wri, sheet_name="COV_ANN_BASE")
        px_close_local[common].to_excel(wri, sheet_name="PRICES_CLOSE_LOCAL")
        px_close_base[common].to_excel(wri, sheet_name="PRICES_CLOSE_BASE")

        # Meta FX
        pd.DataFrame({
            "Ticker": val_df["Ticker"],
            "FX_spot(fin→val)":[ fx_spot(str(val_df.loc[i,"FinancialCCY"]), valuation_ccy) if "FinancialCCY" in val_df.columns else np.nan
                                for i in range(len(val_df)) ]
        }).to_excel(wri, sheet_name="FX_META", index=False)

        # === SUPUESTOS & FUENTES ===
        pd.DataFrame({
            "Clave": ["YEARS_PROJ","FADE_METHOD","LAMBDA","RF_SOURCE","ERP_SOURCE"],
            "Valor": [YEARS_PROJ, CFG["FADE_METHOD"], LAMBDA, rf_src, erp_src]
        }).to_excel(wri, sheet_name="SUPUESTOS_Y_FUENTES", index=False)

        # === TODAS LAS CUENTAS (Anual / Trimestral)
        if not all_a.empty: all_a.to_excel(wri, sheet_name="ALL_STATEMENTS_ANNUAL", index=False)
        if not all_q.empty: all_q.to_excel(wri, sheet_name="ALL_STATEMENTS_QTR", index=False)

    print(f"\n✅ Excel creado: {outfile}")

# ==============================================
# Celda 8.1: main() extendido — Payback en meses + Sector específico
# + NUEVO: Años utilidad con growth promedio últimos 4 trimestres (compuesto trimestral)
# Agrega columnas en DCF_VALUATION:
#   - NI_TTM_in_ValCCY
#   - NI_QoQ_Growth_Avg4
#   - Anios_Utilidad_Growth4Q
# ==============================================
def main():
    alias = load_alias_builtin()
    default_list = ["AAPL","MSFT","GOOGL","NVDA","META","TSLA","SPY"]
    raw = input(f"Tickers separados por coma {default_list}: ").strip()
    universe = _parse_tickers(raw) if raw else default_list[:]
    if "SPY" not in universe: universe.append("SPY")

    valuation_ccy = (input("Moneda de VALORACIÓN (USD/MXN/EUR...) [USD]: ").strip().upper() or "USD")
    rf, erp, rf_src, erp_src = get_rf_erp_with_sources(valuation_ccy)
    years_hist = int(input("Años históricos para Σ/β (2-10) [5]: ").strip() or "5")
    risk_mult = float(input("¿Cuántos SPY de riesgo máximo? (σ^2 cap = mult × Var(SPY)) [1.0]: ").strip() or "1.0")
    budget_min = float(input("Inversión mínima (en MONEDA BASE) [10000]: ").strip() or "10000")
    budget_max = float(input("Inversión máxima (en MONEDA BASE) [50000]: ").strip() or "50000")
    thresh_na_ratio = float(input(f"Umbral % precios válidos por ticker (0.5-0.95) [0.70]: ").strip() or "0.70")
    LAMBDA = float(input(f"LAMBDA para MU_ADJ (0-1) [{CFG['LAMBDA']}]: ").strip() or str(CFG["LAMBDA"]))

    fixed_weights = {}
    json_fw = input("Pega JSON de weights fijos (ej: {'AAPL':0.2,'MSFT':0.1}) o Enter: ").strip()
    if json_fw:
        try:
            fw = json.loads(json_fw.replace("'", '"'))
            for k,v in fw.items():
                if k in universe:
                    fixed_weights[k] = float(v)
            print("Pesos fijos por JSON:", fixed_weights)
        except Exception as e:
            print("JSON inválido; se ignora. Error:", e)

    dcf_rows=[]; info_rows=[]; fx_meta_rows=[]

    # ==== helpers ====
    def _months(numer, annual):
        try:
            if numer is None or annual is None: return np.nan
            numer = float(numer); annual = float(annual)
            if not np.isfinite(numer) or not np.isfinite(annual): return np.nan
            if numer <= 0 or annual <= 0: return np.nan
            return (numer / annual) * 12.0
        except Exception:
            return np.nan

    def _ni_growth4q_years_payback(tk: yf.Ticker, info: dict, alias: dict, valuation_ccy: str, target_equity_val: float):
        """
        Calcula:
        - NI_TTM (sum de últimos 4 trimestres) en ValCCY
        - growth promedio QoQ de los últimos 4 trimestres (usa 5 trimestres para 4 growths)
        - "Años utilidad" = #años hasta que la suma de NI proyectada (compuesto trimestral) alcance target_equity_val

        Si no hay datos o NI<=0, devuelve NaN.
        """
        try:
            qinc = tk.quarterly_financials
            if not isinstance(qinc, pd.DataFrame) or qinc.empty:
                return np.nan, np.nan, np.nan

            # columnas suelen venir más reciente primero; si no, ordenamos desc
            cols = list(qinc.columns)
            if len(cols) < 5:
                return np.nan, np.nan, np.nan
            try:
                cols = sorted(cols, reverse=True)
            except Exception:
                pass

            # extraer net income trimestral por alias
            qni=[]
            for c in cols[:8]:  # tomamos hasta 8 por si hay gaps
                v, _, _ = find_value(qinc, alias["net_income"], c)
                qni.append(v)

            # limpiar: mantener finitos
            qni = [float(x) for x in qni if x is not None and np.isfinite(x)]
            if len(qni) < 5:
                return np.nan, np.nan, np.nan

            # growth QoQ: (q0/q1 - 1), (q1/q2 -1), (q2/q3 -1), (q3/q4 -1)
            grows=[]
            for i in range(4):
                a = qni[i]
                b = qni[i+1]
                if np.isfinite(a) and np.isfinite(b) and b != 0:
                    g = (a / b) - 1.0
                    if np.isfinite(g):
                        grows.append(g)

            if len(grows) == 0:
                g_avg = 0.0
            else:
                g_avg = float(np.mean(grows))

            # clip para evitar explosiones absurdas pero "sin miedo"
            g_avg = float(np.clip(g_avg, -0.75, 1.50))

            # NI TTM (4Q) y spot FX
            fin_ccy = (info.get("financialCurrency") or info.get("currency") or valuation_ccy).upper()
            spot = fx_spot(fin_ccy, valuation_ccy)
            ni_ttm_fin = float(sum(qni[:4]))
            ni_ttm_val = ni_ttm_fin * spot if np.isfinite(ni_ttm_fin) else np.nan

            # payback con utilidad proyectada (trimestral compuesto)
            if (not np.isfinite(target_equity_val)) or target_equity_val <= 0:
                return ni_ttm_val, g_avg, np.nan

            # base: último trimestre (más reciente)
            q0_fin = float(qni[0])
            q0_val = q0_fin * spot

            # si utilidad no positiva, no tiene sentido “años utilidad”
            if (not np.isfinite(q0_val)) or (q0_val <= 0):
                return ni_ttm_val, g_avg, np.nan

            cum = 0.0
            q_proj = q0_val
            max_quarters = 400  # 100 años max
            for k in range(1, max_quarters+1):
                # proyectar siguiente trimestre
                q_proj = q_proj * (1.0 + g_avg)
                if not np.isfinite(q_proj):
                    return ni_ttm_val, g_avg, np.nan
                # si se vuelve <=0 por growth negativo fuerte, cortar
                if q_proj <= 0:
                    return ni_ttm_val, g_avg, np.nan
                cum += q_proj
                if cum >= target_equity_val:
                    return ni_ttm_val, g_avg, float(k/4.0)

            return ni_ttm_val, g_avg, np.nan
        except Exception:
            return np.nan, np.nan, np.nan

    # ==== Valuación por ticker ====
    for sym in universe:
        try:
            tk = yf.Ticker(sym)
            info = tk.info or {}
            price_ccy = (info.get("currency") or valuation_ccy).upper()
            price_ccy, _, _ = normalize_price_currency(price_ccy, None, None)

            sector  = info.get("sector") or ""
            industry= info.get("industry") or ""

            fund = is_etf_or_index(sym, info)
            sector_l  = (sector or "").lower()
            industry_l= (industry or "").lower()
            is_bank_insurer_reit = any(x in industry_l for x in ["bank", "insurance", "reit"]) \
                                   or any(x in sector_l for x in ["banks", "insurance", "reit"])

            # Overrides: forzar DCF industrial si lo deseas
            if sym in {"BRK-A", "BRK-B", "COIN"}:
                is_bank_insurer_reit = False

            # --- Ejecutar modelo de valuación ---
            fields_used = None
            if fund:
                intrinsic, meta, market_px, note = compute_etf_index_intrinsic(
                    tk, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src
                )
            else:
                fields = extract_time_series_v4(tk, 6, alias); fields_used = fields
                if is_bank_insurer_reit:
                    intrinsic, meta, market_px, note = compute_financials_models(
                        tk, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src, alias
                    )
                    if fields_used is None or ("_no_statements_" in fields_used):
                        fields_used = extract_time_series_v4(tk, 6, alias)
                else:
                    intrinsic, meta, market_px, note = compute_dcf_industrial(
                        tk, fields, price_ccy, valuation_ccy, rf, erp, rf_src, erp_src,
                        fade_h=YEARS_PROJ, fade_method=CFG["FADE_METHOD"]
                    )

            if np.isnan(intrinsic) or np.isnan(market_px):
                log.warning(f"{sym}: sin precio intrínseco/mercado válido → omitido")
                continue

            # Dividendos y extremos 5y
            div_ttm, div_y = dividend_ttm(tk, market_px)
            try:
                hist = tk.history(period="5y", auto_adjust=True)["Close"].dropna()
                price_ccy, hist , _ = normalize_price_currency(price_ccy, hist, None)
                max5 = float(hist.max()) if not hist.empty else np.nan
                min5 = float(hist.min()) if not hist.empty else np.nan
            except Exception:
                max5=min5=np.nan
            ptomax = (market_px/max5) if (max5 and max5>0) else np.nan
            ptomin = (market_px/min5) if (min5 and min5>0) else np.nan
            over_ratio = (market_px/intrinsic) if (market_px and intrinsic and intrinsic>0) else np.nan

            # Señal DCF → expected returns
            alpha_dcf = np.nan
            try:
                alpha_dcf = (intrinsic/market_px) - 1.0 if (intrinsic and market_px and market_px>0) else np.nan
            except Exception:
                pass

            # === Cálculos para columnas nuevas (ya existentes en tu 8.1) ===
            fin_ccy = meta.get("fin_ccy", valuation_ccy)

            ni_last_val = np.nan
            try:
                f_ni = fields_used if isinstance(fields_used, dict) else extract_time_series_v4(tk, 6, alias)
                ni_last = first_non_nan(f_ni.get("net_income",[]), np.nan)
                if np.isfinite(ni_last):
                    ni_last_val = float(ni_last) * fx_spot((info.get("financialCurrency") or fin_ccy), valuation_ccy)
            except Exception:
                pass

            # EV aproximado con info de meta: EV = E + Deuda Bruta - Caja
            E_val   = meta.get("E", np.nan)
            D_gross = meta.get("D_gross", np.nan)
            Cash_v  = meta.get("Cash", np.nan)
            try:
                EV_val = float(E_val) + float(D_gross) - float(Cash_v)
            except Exception:
                EV_val = np.nan

            meses_ev_fcff = _months(EV_val, meta.get("FCFF0", np.nan))
            meses_eq_ni   = _months(E_val, ni_last_val)

            # === NUEVO: Años utilidad con growth promedio últimos 4 trimestres (compuesto trimestral) ===
            ni_ttm_val, g_q_avg4, anios_utilidad_g4 = _ni_growth4q_years_payback(
                tk=tk,
                info=info,
                alias=alias,
                valuation_ccy=valuation_ccy,
                target_equity_val=E_val  # “mkt cap” en moneda base (igual que E_val)
            )

            dcf_rows.append({
                "Ticker": sym, "IsFundOrIndex": fund,
                "Price": market_px, "PriceCCY": price_ccy,
                "IntrinsicPrice_in_PriceCCY": intrinsic, "OverValRatio": over_ratio,
                "Price_to_Max": ptomax, "Price_to_Min": ptomin,
                "Div_TTM_per_share": div_ttm, "Dividend_Yield": div_y,
                "Beta_Calc": meta.get("beta_calc", np.nan), "Beta_Info": meta.get("beta_info", np.nan),
                "Beta_Used": meta.get("beta_used", np.nan), "BETA_R2": meta.get("beta_R2", np.nan),
                "BETA_N": meta.get("beta_N", np.nan), "BETA_SOURCE": meta.get("beta_source",""),
                "Return_CAPM": meta.get("Re", np.nan),
                "WACC": meta.get("WACC", np.nan), "Kd": meta.get("Rd", np.nan),
                "Kd_eff": meta.get("Rd_eff", np.nan), "TaxRate": meta.get("tax_rate", np.nan),
                "ETR_3Y_MEDIAN": meta.get("ETR_3Y_MEDIAN", np.nan), "ETR_SOURCE": meta.get("ETR_SOURCE",""),
                "g_exp": meta.get("g_exp", np.nan), "g_term": meta.get("g_term", np.nan),
                "FCFF0_in_valCCY": meta.get("FCFF0", np.nan),
                "ValuationCCY": meta.get("valuation_ccy", valuation_ccy), "FinancialCCY": fin_ccy,
                "RF": meta.get("rf", rf), "ERP": meta.get("erp", erp), "RF_SOURCE": meta.get("rf_source",""), "ERP_SOURCE": meta.get("erp_source",""),
                "E_val": E_val, "D_gross_val": D_gross, "Cash_val": Cash_v,
                "EV_val": EV_val,
                "NI_Last_in_ValCCY": ni_last_val,
                "Meses_EV_por_FCFF0": meses_ev_fcff,
                "Meses_MktCap_por_NI": meses_eq_ni,
                "Sector": sector,
                "Sector_Especifico": industry,

                # ⬇️ NUEVAS columnas solicitadas
                "NI_TTM_in_ValCCY": ni_ttm_val,
                "NI_QoQ_Growth_Avg4": g_q_avg4,
                "Anios_Utilidad_Growth4Q": anios_utilidad_g4,

                "DATA_GAPS": meta.get("DATA_GAPS", False), "ΔNWC_METHOD": meta.get("ΔNWC_METHOD",""),
                "WACC_NET_DEBT?": meta.get("WACC_NET_DEBT", False),
                "SHARES_SOURCE": meta.get("SHARES_SOURCE",""), "CURRENCY_CHECK": meta.get("CURRENCY_CHECK","OK"),
                "Assumptions": meta.get("assumptions",""),
                "DCF_ALPHA_raw": alpha_dcf
            })

            info_rows.append({
                "Ticker": sym, "Precio_real": market_px, "SharesSource": meta.get("SHARES_SOURCE",""),
                "CurrencyCheck": meta.get("CURRENCY_CHECK","OK"),
                "FinancialCCY": fin_ccy, "PriceCCY": price_ccy,
                "Max_5Y": max5, "Min_5Y": min5, "Price_to_Max": ptomax, "Price_to_Min": ptomin,
                "Div_TTM_per_share": div_ttm, "Dividend_Yield": div_y
            })

            fx_meta_rows.append({
                "Ticker": sym, "FinancialCCY": fin_ccy, "ValuationCCY": valuation_ccy,
                "PriceCCY_norm": price_ccy,
                "FX_spot(fin→val)": fx_spot(fin_ccy, valuation_ccy),
                "FX_spot(val→price)": fx_spot(valuation_ccy, price_ccy),
                "Beta_Source": meta.get("beta_source","")
            })
        except Exception as e:
            log.warning(f"Ticker {sym}: {e}")

    val_df = pd.DataFrame(dcf_rows).dropna(subset=["IntrinsicPrice_in_PriceCCY","Price"])
    if val_df.empty:
        raise RuntimeError("Ningún ticker con valoración válida.")

    # Clip robusto para alpha_DCF p5–p95
    if "DCF_ALPHA_raw" in val_df.columns:
        al = val_df["DCF_ALPHA_raw"].astype(float)
        if al.notna().sum()>=5:
            lo, hi = np.nanpercentile(al, 5), np.nanpercentile(al, 95)
            val_df["DCF_ALPHA"] = al.clip(lower=lo, upper=hi)
        else:
            val_df["DCF_ALPHA"] = al
    else:
        val_df["DCF_ALPHA"] = np.nan

    val_df["MU_CAPM"] = val_df["Return_CAPM"].astype(float)
    val_df["MU_ADJ"]  = val_df["MU_CAPM"] + LAMBDA*val_df["DCF_ALPHA"].fillna(0.0)
    val_df["LAMBDA"]  = LAMBDA

    # ====== Precios históricos para Σ ======
    start = (datetime.today() - timedelta(days=years_hist*365+10)).strftime("%Y-%m-%d")
    tickers_px = list(dict.fromkeys(val_df["Ticker"].tolist() + ["SPY"]))
    px_all = yf.download(tickers_px, start=start, auto_adjust=True, progress=False, group_by="ticker")
    if px_all.empty: raise RuntimeError("Precios vacíos.")

    if isinstance(px_all.columns, pd.MultiIndex):
        px_close_local = px_all.xs("Close", level=1, axis=1)
    else:
        one = val_df["Ticker"].tolist()[0]
        px_close_local = px_all["Close"].to_frame(name=one) if "Close" in px_all.columns else None
    if px_close_local is None or px_close_local.empty:
        raise RuntimeError("No se obtuvo 'Close'.")

    def to_base_series(sym, ser):
        p_ccy = (yf.Ticker(sym).info or {}).get("currency") or valuation_ccy
        p_ccy, ser, _ = normalize_price_currency(p_ccy, ser, None)
        if p_ccy != valuation_ccy:
            fx_ser = get_fx_series(p_ccy, valuation_ccy, start).reindex(ser.index, method="ffill").fillna(method="bfill")
            return (ser * fx_ser).dropna()
        return ser

    px_close_base = pd.DataFrame(index=px_close_local.index)
    for sym in px_close_local.columns:
        ser = px_close_local[sym].dropna()
        if ser is not None and len(ser)>0:
            px_close_base[sym] = to_base_series(sym, ser)

    thresh = int(round(len(px_close_base) * thresh_na_ratio))
    px_close_base = px_close_base.dropna(thresh=thresh, axis=1).dropna(how="all")
    present = [t for t in px_close_base.columns if t in val_df["Ticker"].tolist()]
    px_close_base = px_close_base[present]
    if px_close_base.shape[1] < 2:
        raise RuntimeError("Quedaron <2 tickers válidos.")

    ret_d   = px_close_base.pct_change(fill_method=None).dropna()
    cov_ann = ret_d.cov()*252
    vol_ann = pd.Series(np.sqrt(np.diag(cov_ann)), index=cov_ann.index, name="DesvEst_Anual")
    val_df["DesvEst_Anual"] = val_df["Ticker"].map(vol_ann).astype(float)

    var_spy = float(cov_ann.loc["SPY","SPY"]) if "SPY" in cov_ann.index else float(np.nanmean(np.diag(cov_ann.values)))
    sigma_cap = math.sqrt(var_spy * risk_mult) if not np.isnan(var_spy) else None
    ordered   = list(px_close_base.columns)

    mu, Sigma, common = align_mu_sigma(val_df, cov_ann, ordered, mu_col="MU_ADJ")

    bounds = []
    for t in common:
        if t in fixed_weights:
            wfix = max(0.0, min(1.0, float(fixed_weights[t])))
            bounds.append((wfix, wfix))
        else:
            bounds.append((0.0, 1.0))

    w = max_sharpe_with_sigma_cap(mu, Sigma, rf, sigma_cap, bounds=bounds)
    weights = pd.Series(w, index=common, name="Weight").sort_values(ascending=False)

    last_px_base = px_close_base[common].ffill().iloc[-1]
    qty = (weights * budget_max) / last_px_base
    qty = np.floor(qty).astype(int)
    qty = np.where((weights.values > 0) & (qty == 0), 1, qty)
    cost_base = float((qty * last_px_base.loc[weights.index].values).sum())
    if cost_base < budget_min or cost_base > budget_max:
        factor = min(1.0, budget_max/max(cost_base,1e-9))
        qty = np.floor(qty * factor).astype(int)
        cost_base = float((qty * last_px_base.loc[weights.index].values).sum())

    w_vec   = weights.values
    port_ret= float(w_vec @ mu)
    port_vol= float(np.sqrt(w_vec @ cov_ann.loc[common,common].values @ w_vec))
    sharpe  = (port_ret - rf)/port_vol if port_vol>0 else np.nan
    last_px_local = px_close_local[common].ffill().iloc[-1]

    rows_port=[]
    for i,t in enumerate(common):
        p_ccy = (yf.Ticker(t).info or {}).get("currency") or valuation_ccy
        p_ccy, _, _ = normalize_price_currency(p_ccy, None, None)
        rows_port.append({
            "Ticker": t, "Weight": float(weights[t]),
            "LastPrice_Local": float(last_px_local[t]), "PriceCCY": p_ccy,
            "FX_PriceCCY_to_Base": fx_spot(p_ccy, valuation_ccy),
            "LastPrice_Base": float(last_px_base[t]),
            "Qty": int(qty[i]), "Position_Base": float(qty[i]*last_px_base[t]),
        })
    port_df = pd.DataFrame(rows_port)

    # Estados detallados
    all_a, all_q = collect_all_statements_long(common)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    outfile = f"{ts}_{XL_OUT}"
    with pd.ExcelWriter(outfile, engine="xlsxwriter", datetime_format="yyyy-mm-dd") as wri:
        pd.DataFrame(info_rows).to_excel(wri, sheet_name="INFO_ACCIONES", index=False)
        pd.DataFrame(fx_meta_rows).to_excel(wri, sheet_name="FX_APLICADO", index=False)

        # ⬇️ Aquí ya incluye las columnas nuevas:
        val_df.to_excel(wri, sheet_name="DCF_VALUATION", index=False)

        port_df.to_excel(wri, sheet_name="PORTFOLIO_BASE", index=False)
        pd.DataFrame({
            "Sharpe":[sharpe], "Port_Ret":[port_ret], "Port_Vol":[port_vol], "RiskFree":[rf], "ERP":[erp],
            "SigmaCap(SPY)":[sigma_cap], "Var(SPY)_Base":[var_spy],
            "ValuationCCY(Base)":[valuation_ccy], "BudgetMin_Base":[budget_min], "BudgetMax_Base":[budget_max]
        }).to_excel(wri, sheet_name="SUMMARY", index=False)
        pd.DataFrame(cov_ann.loc[common, common]).to_excel(wri, sheet_name="COV_ANN_BASE")
        px_close_local[common].to_excel(wri, sheet_name="PRICES_CLOSE_LOCAL")
        px_close_base[common].to_excel(wri, sheet_name="PRICES_CLOSE_BASE")

        pd.DataFrame({
            "Ticker": val_df["Ticker"],
            "FX_spot(fin→val)":[ fx_spot(str(val_df.loc[i,"FinancialCCY"]), valuation_ccy) if "FinancialCCY" in val_df.columns else np.nan
                                for i in range(len(val_df)) ]
        }).to_excel(wri, sheet_name="FX_META", index=False)

        pd.DataFrame({
            "Clave": ["YEARS_PROJ","FADE_METHOD","LAMBDA","RF_SOURCE","ERP_SOURCE"],
            "Valor": [YEARS_PROJ, CFG["FADE_METHOD"], LAMBDA, rf_src, erp_src]
        }).to_excel(wri, sheet_name="SUPUESTOS_Y_FUENTES", index=False)

        if not all_a.empty: all_a.to_excel(wri, sheet_name="ALL_STATEMENTS_ANNUAL", index=False)
        if not all_q.empty: all_q.to_excel(wri, sheet_name="ALL_STATEMENTS_QTR", index=False)

    print(f"\n✅ Excel creado: {outfile}")

# ==============================================
# Celda 9: PORTAFOLIOS + CONFIG.yml + TEST_PLAN + SMOKE TEST
# ==============================================
def _ensure_db_exists():
    if not os.path.exists(PORTFOLIO_DB_FILE):
        with open(PORTFOLIO_DB_FILE, "w", encoding="utf-8") as f:
            json.dump([], f)

def list_portfolios():
    try:
        _ensure_db_exists()
        lst = json.load(open(PORTFOLIO_DB_FILE, "r", encoding="utf-8"))
        out=[]
        for i,rec in enumerate(lst):
            out.append((i, rec.get("name",""), rec.get("timestamp",""), rec.get("universe",[])))
        return out
    except Exception as e:
        log.warning(f"No se pudo leer {PORTFOLIO_DB_FILE}: {e}")
        return []

def save_portfolio(name: str, universe: List[str], weights: Dict[str,float], qty: Dict[str,int], base_ccy: str):
    try:
        _ensure_db_exists()
        lst = json.load(open(PORTFOLIO_DB_FILE, "r", encoding="utf-8"))
        rec = {
            "name": name, "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "universe": list(universe),
            "weights": {k: float(weights.get(k,0.0)) for k in universe},
            "qty": {k: int(qty.get(k,0)) for k in universe},
            "valuation_ccy": base_ccy
        }
        lst.insert(0, rec); lst = lst[:5]
        json.dump(lst, open(PORTFOLIO_DB_FILE, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        return True
    except Exception as e:
        log.warning(f"save_portfolio error: {e}")
        return False

def write_config_file(path="CONFIG.yml"):
    if yaml is None:
        print("pyyaml no instalado: no se pudo escribir CONFIG.yml automáticamente.")
        return
    yaml.safe_dump(CFG, open(path, "w", encoding="utf-8"))

def write_test_plan(path="TEST_PLAN.md"):
    text = f"""# TEST_PLAN — Smoke Test (reproducible)

## Universo sugerido (multisector/multimoneda)
AAPL, MSFT, GOOGL, NVDA, META, TSLA, BNS.TO, BME.MC, ITUB, HSBC, ^MXX, SPY

## Criterios de aceptación
- `WACC_NET_DEBT? = FALSE` en industriales (pesos con deuda bruta).
- `ETR_SOURCE` = 3Y_MEDIAN o DEFAULT_COUNTRY con cap razonable por país.
- `ΔNWC_METHOD` en ANNUAL_3Y_MEAN / ANNUAL_5Y_MEAN / TTM_4Q (sin signos invertidos).
- `BETA_SOURCE` documenta la elección (CALC vs INFO vs SECTOR_FALLBACK).
- `MU_ADJ` ≠ `MU_CAPM` cuando `DCF_ALPHA` sea material (λ = {CFG["LAMBDA"]}).
- `g_term < WACC` en todos los casos (si no, auto recorte y flag implícito).
- Sin NaN en métricas clave del Excel.
- Desempeño razonable (vectorizado, sin loops innecesarios).

## Pasos
1. Ejecutar Celda 1 → Celda 9 en orden.
2. En `main()`: usar moneda base USD; aceptar RF/ERP por defecto; YEARS_HIST=5; LAMBDA={CFG["LAMBDA"]}.
3. Verificar Excel generado y tabs:
   - DCF_VALUATION: columnas nuevas (`DATA_GAPS`, `ΔNWC_METHOD`, `ETR_SOURCE`,
     `WACC_NET_DEBT?`, `RF_SOURCE`, `ERP_SOURCE`, `BETA_*`, `DCF_ALPHA`, `MU_CAPM`, `MU_ADJ`, `LAMBDA`, `SHARES_SOURCE`, `CURRENCY_CHECK`).
   - INFO_ACCIONES, FX_APLICADO, PORTFOLIO_BASE, SUMMARY, COV_ANN_BASE, PRICES_CLOSE_LOCAL/BASE,
     FX_META, SUPUESTOS_Y_FUENTES, ALL_STATEMENTS_ANNUAL, ALL_STATEMENTS_QTR.

## Notas
- Si `shares = marketCap/price` ⇒ `SHARES_SOURCE = MKTCAP/PX` y `CURRENCY_CHECK = REQUIRED`.
- En industriales: EV→Equity SIEMPRE usa Net Debt, pesos del WACC usan Deuda Bruta.
"""
    open(path, "w", encoding="utf-8").write(text)

def run_smoke_test_quick():
    print("Sugerencia de universo para test:", "AAPL,MSFT,GOOGL,NVDA,META,TSLA,SPY")
    print("Moneda base: USD | YEARS_PROJ:", YEARS_PROJ, "| FADE:", CFG["FADE_METHOD"], "| LAMBDA:", CFG["LAMBDA"])
    print("Lanza main() y sigue prompts…")

# (Opcional) generar archivos auxiliares
# write_config_file("CONFIG.yml")
# write_test_plan("TEST_PLAN.md")

print("✅ Celda 9 lista. Usa run_smoke_test_quick() para guía rápida.")

# ==============================================
# Celda 10: EJECUCIÓN
# ==============================================
if __name__ == "__main__":
    main()

# ==============================================
# Celda EXTRA: DEPURACIÓN DE TICKERS PROBLEMÁTICOS
# ==============================================

test_tickers = ["KKR"]
alias = load_alias_builtin()

for t in test_tickers:
    print(f"\n{'='*30}\nTICKER: {t}\n{'='*30}")
    tk = yf.Ticker(t)

    # 1️⃣ Información general
    info = tk.info or {}
    print("currency:", info.get("currency"))
    print("financialCurrency:", info.get("financialCurrency"))
    print("country:", info.get("country"))
    print("sector:", info.get("sector"))
    print("sharesOutstanding:", info.get("sharesOutstanding"))
    print("marketCap:", info.get("marketCap"))

    # 2️⃣ Estados financieros
    fin = tk.financials
    bal = tk.balance_sheet
    cf  = tk.cashflow
    print(f"Financials empty? {fin.empty if fin is not None else 'None'}")
    print(f"Balance empty? {bal.empty if bal is not None else 'None'}")
    print(f"Cashflow empty? {cf.empty if cf is not None else 'None'}")

    # 3️⃣ Primeros campos encontrados
    try:
        flds = extract_time_series_v4(tk, 5, alias)
        print("Keys extraídas:", list(flds.keys())[:10])
        print("EBIT sample:", flds.get('ebit', [])[:3])
        print("DA sample:", flds.get('da', [])[:3])
        print("CAPEX sample:", flds.get('capex', [])[:3])
        print("ΔNWC sample:", flds.get('delta_nwc', [])[:3])
        print("Cash_last:", flds.get('cash_last'))
        print("Debt_total_last:", flds.get('debt_total_last'))
    except Exception as e:
        print("Error en extract_time_series_v4:", e)

    # 4️⃣ Prueba rápida de DCF (si aplica)
    try:
        rf, erp, rf_src, erp_src = 0.04, 0.055, "DEFAULT", "DEFAULT"
        val, meta, px, note = compute_dcf_industrial(
            tk, flds, info.get("currency","USD"), "USD", rf, erp, rf_src, erp_src
        )
        print("DCF Intrinsic:", val, "| Precio:", px, "| Note:", note)
    except Exception as e:
        print("Error DCF:", e)